/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables;


import com.jooq.example.domain.Indexes;
import com.jooq.example.domain.Keys;
import com.jooq.example.domain.Northwind;
import com.jooq.example.domain.tables.records.OrdersTaxStatusRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersTaxStatus extends TableImpl<OrdersTaxStatusRecord> {

    private static final long serialVersionUID = 798047560;

    /**
     * The reference instance of <code>northwind.orders_tax_status</code>
     */
    public static final OrdersTaxStatus ORDERS_TAX_STATUS = new OrdersTaxStatus();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrdersTaxStatusRecord> getRecordType() {
        return OrdersTaxStatusRecord.class;
    }

    /**
     * The column <code>northwind.orders_tax_status.id</code>.
     */
    public final TableField<OrdersTaxStatusRecord, Byte> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>northwind.orders_tax_status.tax_status_name</code>.
     */
    public final TableField<OrdersTaxStatusRecord, String> TAX_STATUS_NAME = createField(DSL.name("tax_status_name"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * Create a <code>northwind.orders_tax_status</code> table reference
     */
    public OrdersTaxStatus() {
        this(DSL.name("orders_tax_status"), null);
    }

    /**
     * Create an aliased <code>northwind.orders_tax_status</code> table reference
     */
    public OrdersTaxStatus(String alias) {
        this(DSL.name(alias), ORDERS_TAX_STATUS);
    }

    /**
     * Create an aliased <code>northwind.orders_tax_status</code> table reference
     */
    public OrdersTaxStatus(Name alias) {
        this(alias, ORDERS_TAX_STATUS);
    }

    private OrdersTaxStatus(Name alias, Table<OrdersTaxStatusRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrdersTaxStatus(Name alias, Table<OrdersTaxStatusRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OrdersTaxStatus(Table<O> child, ForeignKey<O, OrdersTaxStatusRecord> key) {
        super(child, key, ORDERS_TAX_STATUS);
    }

    @Override
    public Schema getSchema() {
        return Northwind.NORTHWIND;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ORDERS_TAX_STATUS_PRIMARY);
    }

    @Override
    public UniqueKey<OrdersTaxStatusRecord> getPrimaryKey() {
        return Keys.KEY_ORDERS_TAX_STATUS_PRIMARY;
    }

    @Override
    public List<UniqueKey<OrdersTaxStatusRecord>> getKeys() {
        return Arrays.<UniqueKey<OrdersTaxStatusRecord>>asList(Keys.KEY_ORDERS_TAX_STATUS_PRIMARY);
    }

    @Override
    public OrdersTaxStatus as(String alias) {
        return new OrdersTaxStatus(DSL.name(alias), this);
    }

    @Override
    public OrdersTaxStatus as(Name alias) {
        return new OrdersTaxStatus(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrdersTaxStatus rename(String name) {
        return new OrdersTaxStatus(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrdersTaxStatus rename(Name name) {
        return new OrdersTaxStatus(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Byte, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
