/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables;


import com.jooq.example.domain.Indexes;
import com.jooq.example.domain.Keys;
import com.jooq.example.domain.Northwind;
import com.jooq.example.domain.tables.records.StringsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Strings extends TableImpl<StringsRecord> {

    private static final long serialVersionUID = -1735952418;

    /**
     * The reference instance of <code>northwind.strings</code>
     */
    public static final Strings STRINGS = new Strings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StringsRecord> getRecordType() {
        return StringsRecord.class;
    }

    /**
     * The column <code>northwind.strings.string_id</code>.
     */
    public final TableField<StringsRecord, Integer> STRING_ID = createField(DSL.name("string_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>northwind.strings.string_data</code>.
     */
    public final TableField<StringsRecord, String> STRING_DATA = createField(DSL.name("string_data"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>northwind.strings</code> table reference
     */
    public Strings() {
        this(DSL.name("strings"), null);
    }

    /**
     * Create an aliased <code>northwind.strings</code> table reference
     */
    public Strings(String alias) {
        this(DSL.name(alias), STRINGS);
    }

    /**
     * Create an aliased <code>northwind.strings</code> table reference
     */
    public Strings(Name alias) {
        this(alias, STRINGS);
    }

    private Strings(Name alias, Table<StringsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Strings(Name alias, Table<StringsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Strings(Table<O> child, ForeignKey<O, StringsRecord> key) {
        super(child, key, STRINGS);
    }

    @Override
    public Schema getSchema() {
        return Northwind.NORTHWIND;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STRINGS_PRIMARY);
    }

    @Override
    public Identity<StringsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STRINGS;
    }

    @Override
    public UniqueKey<StringsRecord> getPrimaryKey() {
        return Keys.KEY_STRINGS_PRIMARY;
    }

    @Override
    public List<UniqueKey<StringsRecord>> getKeys() {
        return Arrays.<UniqueKey<StringsRecord>>asList(Keys.KEY_STRINGS_PRIMARY);
    }

    @Override
    public Strings as(String alias) {
        return new Strings(DSL.name(alias), this);
    }

    @Override
    public Strings as(Name alias) {
        return new Strings(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Strings rename(String name) {
        return new Strings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Strings rename(Name name) {
        return new Strings(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
