/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables;


import com.jooq.example.domain.Indexes;
import com.jooq.example.domain.Keys;
import com.jooq.example.domain.Northwind;
import com.jooq.example.domain.tables.records.SuppliersRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row18;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Suppliers extends TableImpl<SuppliersRecord> {

    private static final long serialVersionUID = -1341125552;

    /**
     * The reference instance of <code>northwind.suppliers</code>
     */
    public static final Suppliers SUPPLIERS = new Suppliers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SuppliersRecord> getRecordType() {
        return SuppliersRecord.class;
    }

    /**
     * The column <code>northwind.suppliers.id</code>.
     */
    public final TableField<SuppliersRecord, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>northwind.suppliers.company</code>.
     */
    public final TableField<SuppliersRecord, String> COMPANY = createField(DSL.name("company"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>northwind.suppliers.last_name</code>.
     */
    public final TableField<SuppliersRecord, String> LAST_NAME = createField(DSL.name("last_name"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>northwind.suppliers.first_name</code>.
     */
    public final TableField<SuppliersRecord, String> FIRST_NAME = createField(DSL.name("first_name"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>northwind.suppliers.email_address</code>.
     */
    public final TableField<SuppliersRecord, String> EMAIL_ADDRESS = createField(DSL.name("email_address"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>northwind.suppliers.job_title</code>.
     */
    public final TableField<SuppliersRecord, String> JOB_TITLE = createField(DSL.name("job_title"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>northwind.suppliers.business_phone</code>.
     */
    public final TableField<SuppliersRecord, String> BUSINESS_PHONE = createField(DSL.name("business_phone"), org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * The column <code>northwind.suppliers.home_phone</code>.
     */
    public final TableField<SuppliersRecord, String> HOME_PHONE = createField(DSL.name("home_phone"), org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * The column <code>northwind.suppliers.mobile_phone</code>.
     */
    public final TableField<SuppliersRecord, String> MOBILE_PHONE = createField(DSL.name("mobile_phone"), org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * The column <code>northwind.suppliers.fax_number</code>.
     */
    public final TableField<SuppliersRecord, String> FAX_NUMBER = createField(DSL.name("fax_number"), org.jooq.impl.SQLDataType.VARCHAR(25), this, "");

    /**
     * The column <code>northwind.suppliers.address</code>.
     */
    public final TableField<SuppliersRecord, String> ADDRESS = createField(DSL.name("address"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>northwind.suppliers.city</code>.
     */
    public final TableField<SuppliersRecord, String> CITY = createField(DSL.name("city"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>northwind.suppliers.state_province</code>.
     */
    public final TableField<SuppliersRecord, String> STATE_PROVINCE = createField(DSL.name("state_province"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>northwind.suppliers.zip_postal_code</code>.
     */
    public final TableField<SuppliersRecord, String> ZIP_POSTAL_CODE = createField(DSL.name("zip_postal_code"), org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>northwind.suppliers.country_region</code>.
     */
    public final TableField<SuppliersRecord, String> COUNTRY_REGION = createField(DSL.name("country_region"), org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>northwind.suppliers.web_page</code>.
     */
    public final TableField<SuppliersRecord, String> WEB_PAGE = createField(DSL.name("web_page"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>northwind.suppliers.notes</code>.
     */
    public final TableField<SuppliersRecord, String> NOTES = createField(DSL.name("notes"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>northwind.suppliers.attachments</code>.
     */
    public final TableField<SuppliersRecord, byte[]> ATTACHMENTS = createField(DSL.name("attachments"), org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * Create a <code>northwind.suppliers</code> table reference
     */
    public Suppliers() {
        this(DSL.name("suppliers"), null);
    }

    /**
     * Create an aliased <code>northwind.suppliers</code> table reference
     */
    public Suppliers(String alias) {
        this(DSL.name(alias), SUPPLIERS);
    }

    /**
     * Create an aliased <code>northwind.suppliers</code> table reference
     */
    public Suppliers(Name alias) {
        this(alias, SUPPLIERS);
    }

    private Suppliers(Name alias, Table<SuppliersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Suppliers(Name alias, Table<SuppliersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Suppliers(Table<O> child, ForeignKey<O, SuppliersRecord> key) {
        super(child, key, SUPPLIERS);
    }

    @Override
    public Schema getSchema() {
        return Northwind.NORTHWIND;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SUPPLIERS_CITY, Indexes.SUPPLIERS_COMPANY, Indexes.SUPPLIERS_FIRST_NAME, Indexes.SUPPLIERS_LAST_NAME, Indexes.SUPPLIERS_PRIMARY, Indexes.SUPPLIERS_STATE_PROVINCE, Indexes.SUPPLIERS_ZIP_POSTAL_CODE);
    }

    @Override
    public Identity<SuppliersRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SUPPLIERS;
    }

    @Override
    public UniqueKey<SuppliersRecord> getPrimaryKey() {
        return Keys.KEY_SUPPLIERS_PRIMARY;
    }

    @Override
    public List<UniqueKey<SuppliersRecord>> getKeys() {
        return Arrays.<UniqueKey<SuppliersRecord>>asList(Keys.KEY_SUPPLIERS_PRIMARY);
    }

    @Override
    public Suppliers as(String alias) {
        return new Suppliers(DSL.name(alias), this);
    }

    @Override
    public Suppliers as(Name alias) {
        return new Suppliers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Suppliers rename(String name) {
        return new Suppliers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Suppliers rename(Name name) {
        return new Suppliers(name, null);
    }

    // -------------------------------------------------------------------------
    // Row18 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row18<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, byte[]> fieldsRow() {
        return (Row18) super.fieldsRow();
    }
}
