/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain;


import com.jooq.example.domain.tables.Customers;
import com.jooq.example.domain.tables.EmployeePrivileges;
import com.jooq.example.domain.tables.Employees;
import com.jooq.example.domain.tables.InventoryTransactionTypes;
import com.jooq.example.domain.tables.InventoryTransactions;
import com.jooq.example.domain.tables.Invoices;
import com.jooq.example.domain.tables.OrderDetails;
import com.jooq.example.domain.tables.OrderDetailsStatus;
import com.jooq.example.domain.tables.Orders;
import com.jooq.example.domain.tables.OrdersStatus;
import com.jooq.example.domain.tables.OrdersTaxStatus;
import com.jooq.example.domain.tables.Privileges;
import com.jooq.example.domain.tables.Products;
import com.jooq.example.domain.tables.PurchaseOrderDetails;
import com.jooq.example.domain.tables.PurchaseOrderStatus;
import com.jooq.example.domain.tables.PurchaseOrders;
import com.jooq.example.domain.tables.SalesReports;
import com.jooq.example.domain.tables.Shippers;
import com.jooq.example.domain.tables.Strings;
import com.jooq.example.domain.tables.Suppliers;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>northwind</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CUSTOMERS_CITY = Indexes0.CUSTOMERS_CITY;
    public static final Index CUSTOMERS_COMPANY = Indexes0.CUSTOMERS_COMPANY;
    public static final Index CUSTOMERS_FIRST_NAME = Indexes0.CUSTOMERS_FIRST_NAME;
    public static final Index CUSTOMERS_LAST_NAME = Indexes0.CUSTOMERS_LAST_NAME;
    public static final Index CUSTOMERS_PRIMARY = Indexes0.CUSTOMERS_PRIMARY;
    public static final Index CUSTOMERS_STATE_PROVINCE = Indexes0.CUSTOMERS_STATE_PROVINCE;
    public static final Index CUSTOMERS_ZIP_POSTAL_CODE = Indexes0.CUSTOMERS_ZIP_POSTAL_CODE;
    public static final Index EMPLOYEES_CITY = Indexes0.EMPLOYEES_CITY;
    public static final Index EMPLOYEES_COMPANY = Indexes0.EMPLOYEES_COMPANY;
    public static final Index EMPLOYEES_FIRST_NAME = Indexes0.EMPLOYEES_FIRST_NAME;
    public static final Index EMPLOYEES_LAST_NAME = Indexes0.EMPLOYEES_LAST_NAME;
    public static final Index EMPLOYEES_PRIMARY = Indexes0.EMPLOYEES_PRIMARY;
    public static final Index EMPLOYEES_STATE_PROVINCE = Indexes0.EMPLOYEES_STATE_PROVINCE;
    public static final Index EMPLOYEES_ZIP_POSTAL_CODE = Indexes0.EMPLOYEES_ZIP_POSTAL_CODE;
    public static final Index EMPLOYEE_PRIVILEGES_EMPLOYEE_ID = Indexes0.EMPLOYEE_PRIVILEGES_EMPLOYEE_ID;
    public static final Index EMPLOYEE_PRIVILEGES_PRIMARY = Indexes0.EMPLOYEE_PRIVILEGES_PRIMARY;
    public static final Index EMPLOYEE_PRIVILEGES_PRIVILEGE_ID = Indexes0.EMPLOYEE_PRIVILEGES_PRIVILEGE_ID;
    public static final Index EMPLOYEE_PRIVILEGES_PRIVILEGE_ID_2 = Indexes0.EMPLOYEE_PRIVILEGES_PRIVILEGE_ID_2;
    public static final Index INVENTORY_TRANSACTIONS_CUSTOMER_ORDER_ID = Indexes0.INVENTORY_TRANSACTIONS_CUSTOMER_ORDER_ID;
    public static final Index INVENTORY_TRANSACTIONS_CUSTOMER_ORDER_ID_2 = Indexes0.INVENTORY_TRANSACTIONS_CUSTOMER_ORDER_ID_2;
    public static final Index INVENTORY_TRANSACTIONS_PRIMARY = Indexes0.INVENTORY_TRANSACTIONS_PRIMARY;
    public static final Index INVENTORY_TRANSACTIONS_PRODUCT_ID = Indexes0.INVENTORY_TRANSACTIONS_PRODUCT_ID;
    public static final Index INVENTORY_TRANSACTIONS_PRODUCT_ID_2 = Indexes0.INVENTORY_TRANSACTIONS_PRODUCT_ID_2;
    public static final Index INVENTORY_TRANSACTIONS_PURCHASE_ORDER_ID = Indexes0.INVENTORY_TRANSACTIONS_PURCHASE_ORDER_ID;
    public static final Index INVENTORY_TRANSACTIONS_PURCHASE_ORDER_ID_2 = Indexes0.INVENTORY_TRANSACTIONS_PURCHASE_ORDER_ID_2;
    public static final Index INVENTORY_TRANSACTIONS_TRANSACTION_TYPE = Indexes0.INVENTORY_TRANSACTIONS_TRANSACTION_TYPE;
    public static final Index INVENTORY_TRANSACTION_TYPES_PRIMARY = Indexes0.INVENTORY_TRANSACTION_TYPES_PRIMARY;
    public static final Index INVOICES_FK_INVOICES_ORDERS1_IDX = Indexes0.INVOICES_FK_INVOICES_ORDERS1_IDX;
    public static final Index INVOICES_ID = Indexes0.INVOICES_ID;
    public static final Index INVOICES_ID_2 = Indexes0.INVOICES_ID_2;
    public static final Index INVOICES_PRIMARY = Indexes0.INVOICES_PRIMARY;
    public static final Index ORDERS_CUSTOMER_ID = Indexes0.ORDERS_CUSTOMER_ID;
    public static final Index ORDERS_CUSTOMER_ID_2 = Indexes0.ORDERS_CUSTOMER_ID_2;
    public static final Index ORDERS_EMPLOYEE_ID = Indexes0.ORDERS_EMPLOYEE_ID;
    public static final Index ORDERS_EMPLOYEE_ID_2 = Indexes0.ORDERS_EMPLOYEE_ID_2;
    public static final Index ORDERS_FK_ORDERS_ORDERS_STATUS1 = Indexes0.ORDERS_FK_ORDERS_ORDERS_STATUS1;
    public static final Index ORDERS_ID = Indexes0.ORDERS_ID;
    public static final Index ORDERS_ID_2 = Indexes0.ORDERS_ID_2;
    public static final Index ORDERS_ID_3 = Indexes0.ORDERS_ID_3;
    public static final Index ORDERS_PRIMARY = Indexes0.ORDERS_PRIMARY;
    public static final Index ORDERS_SHIPPER_ID = Indexes0.ORDERS_SHIPPER_ID;
    public static final Index ORDERS_SHIPPER_ID_2 = Indexes0.ORDERS_SHIPPER_ID_2;
    public static final Index ORDERS_SHIP_ZIP_POSTAL_CODE = Indexes0.ORDERS_SHIP_ZIP_POSTAL_CODE;
    public static final Index ORDERS_TAX_STATUS = Indexes0.ORDERS_TAX_STATUS;
    public static final Index ORDERS_STATUS_PRIMARY = Indexes0.ORDERS_STATUS_PRIMARY;
    public static final Index ORDERS_TAX_STATUS_PRIMARY = Indexes0.ORDERS_TAX_STATUS_PRIMARY;
    public static final Index ORDER_DETAILS_FK_ORDER_DETAILS_ORDERS1_IDX = Indexes0.ORDER_DETAILS_FK_ORDER_DETAILS_ORDERS1_IDX;
    public static final Index ORDER_DETAILS_FK_ORDER_DETAILS_ORDER_DETAILS_STATUS1_IDX = Indexes0.ORDER_DETAILS_FK_ORDER_DETAILS_ORDER_DETAILS_STATUS1_IDX;
    public static final Index ORDER_DETAILS_ID = Indexes0.ORDER_DETAILS_ID;
    public static final Index ORDER_DETAILS_ID_2 = Indexes0.ORDER_DETAILS_ID_2;
    public static final Index ORDER_DETAILS_ID_3 = Indexes0.ORDER_DETAILS_ID_3;
    public static final Index ORDER_DETAILS_ID_4 = Indexes0.ORDER_DETAILS_ID_4;
    public static final Index ORDER_DETAILS_ID_5 = Indexes0.ORDER_DETAILS_ID_5;
    public static final Index ORDER_DETAILS_INVENTORY_ID = Indexes0.ORDER_DETAILS_INVENTORY_ID;
    public static final Index ORDER_DETAILS_PRIMARY = Indexes0.ORDER_DETAILS_PRIMARY;
    public static final Index ORDER_DETAILS_PRODUCT_ID = Indexes0.ORDER_DETAILS_PRODUCT_ID;
    public static final Index ORDER_DETAILS_PRODUCT_ID_2 = Indexes0.ORDER_DETAILS_PRODUCT_ID_2;
    public static final Index ORDER_DETAILS_PURCHASE_ORDER_ID = Indexes0.ORDER_DETAILS_PURCHASE_ORDER_ID;
    public static final Index ORDER_DETAILS_STATUS_PRIMARY = Indexes0.ORDER_DETAILS_STATUS_PRIMARY;
    public static final Index PRIVILEGES_PRIMARY = Indexes0.PRIVILEGES_PRIMARY;
    public static final Index PRODUCTS_PRIMARY = Indexes0.PRODUCTS_PRIMARY;
    public static final Index PRODUCTS_PRODUCT_CODE = Indexes0.PRODUCTS_PRODUCT_CODE;
    public static final Index PURCHASE_ORDERS_CREATED_BY = Indexes0.PURCHASE_ORDERS_CREATED_BY;
    public static final Index PURCHASE_ORDERS_ID = Indexes0.PURCHASE_ORDERS_ID;
    public static final Index PURCHASE_ORDERS_ID_2 = Indexes0.PURCHASE_ORDERS_ID_2;
    public static final Index PURCHASE_ORDERS_PRIMARY = Indexes0.PURCHASE_ORDERS_PRIMARY;
    public static final Index PURCHASE_ORDERS_STATUS_ID = Indexes0.PURCHASE_ORDERS_STATUS_ID;
    public static final Index PURCHASE_ORDERS_SUPPLIER_ID = Indexes0.PURCHASE_ORDERS_SUPPLIER_ID;
    public static final Index PURCHASE_ORDERS_SUPPLIER_ID_2 = Indexes0.PURCHASE_ORDERS_SUPPLIER_ID_2;
    public static final Index PURCHASE_ORDER_DETAILS_ID = Indexes0.PURCHASE_ORDER_DETAILS_ID;
    public static final Index PURCHASE_ORDER_DETAILS_INVENTORY_ID = Indexes0.PURCHASE_ORDER_DETAILS_INVENTORY_ID;
    public static final Index PURCHASE_ORDER_DETAILS_INVENTORY_ID_2 = Indexes0.PURCHASE_ORDER_DETAILS_INVENTORY_ID_2;
    public static final Index PURCHASE_ORDER_DETAILS_PRIMARY = Indexes0.PURCHASE_ORDER_DETAILS_PRIMARY;
    public static final Index PURCHASE_ORDER_DETAILS_PRODUCT_ID = Indexes0.PURCHASE_ORDER_DETAILS_PRODUCT_ID;
    public static final Index PURCHASE_ORDER_DETAILS_PRODUCT_ID_2 = Indexes0.PURCHASE_ORDER_DETAILS_PRODUCT_ID_2;
    public static final Index PURCHASE_ORDER_DETAILS_PURCHASE_ORDER_ID = Indexes0.PURCHASE_ORDER_DETAILS_PURCHASE_ORDER_ID;
    public static final Index PURCHASE_ORDER_DETAILS_PURCHASE_ORDER_ID_2 = Indexes0.PURCHASE_ORDER_DETAILS_PURCHASE_ORDER_ID_2;
    public static final Index PURCHASE_ORDER_STATUS_PRIMARY = Indexes0.PURCHASE_ORDER_STATUS_PRIMARY;
    public static final Index SALES_REPORTS_PRIMARY = Indexes0.SALES_REPORTS_PRIMARY;
    public static final Index SHIPPERS_CITY = Indexes0.SHIPPERS_CITY;
    public static final Index SHIPPERS_COMPANY = Indexes0.SHIPPERS_COMPANY;
    public static final Index SHIPPERS_FIRST_NAME = Indexes0.SHIPPERS_FIRST_NAME;
    public static final Index SHIPPERS_LAST_NAME = Indexes0.SHIPPERS_LAST_NAME;
    public static final Index SHIPPERS_PRIMARY = Indexes0.SHIPPERS_PRIMARY;
    public static final Index SHIPPERS_STATE_PROVINCE = Indexes0.SHIPPERS_STATE_PROVINCE;
    public static final Index SHIPPERS_ZIP_POSTAL_CODE = Indexes0.SHIPPERS_ZIP_POSTAL_CODE;
    public static final Index STRINGS_PRIMARY = Indexes0.STRINGS_PRIMARY;
    public static final Index SUPPLIERS_CITY = Indexes0.SUPPLIERS_CITY;
    public static final Index SUPPLIERS_COMPANY = Indexes0.SUPPLIERS_COMPANY;
    public static final Index SUPPLIERS_FIRST_NAME = Indexes0.SUPPLIERS_FIRST_NAME;
    public static final Index SUPPLIERS_LAST_NAME = Indexes0.SUPPLIERS_LAST_NAME;
    public static final Index SUPPLIERS_PRIMARY = Indexes0.SUPPLIERS_PRIMARY;
    public static final Index SUPPLIERS_STATE_PROVINCE = Indexes0.SUPPLIERS_STATE_PROVINCE;
    public static final Index SUPPLIERS_ZIP_POSTAL_CODE = Indexes0.SUPPLIERS_ZIP_POSTAL_CODE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CUSTOMERS_CITY = Internal.createIndex("city", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.CITY }, false);
        public static Index CUSTOMERS_COMPANY = Internal.createIndex("company", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.COMPANY }, false);
        public static Index CUSTOMERS_FIRST_NAME = Internal.createIndex("first_name", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.FIRST_NAME }, false);
        public static Index CUSTOMERS_LAST_NAME = Internal.createIndex("last_name", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.LAST_NAME }, false);
        public static Index CUSTOMERS_PRIMARY = Internal.createIndex("PRIMARY", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.ID }, true);
        public static Index CUSTOMERS_STATE_PROVINCE = Internal.createIndex("state_province", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.STATE_PROVINCE }, false);
        public static Index CUSTOMERS_ZIP_POSTAL_CODE = Internal.createIndex("zip_postal_code", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.ZIP_POSTAL_CODE }, false);
        public static Index EMPLOYEES_CITY = Internal.createIndex("city", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.CITY }, false);
        public static Index EMPLOYEES_COMPANY = Internal.createIndex("company", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.COMPANY }, false);
        public static Index EMPLOYEES_FIRST_NAME = Internal.createIndex("first_name", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.FIRST_NAME }, false);
        public static Index EMPLOYEES_LAST_NAME = Internal.createIndex("last_name", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.LAST_NAME }, false);
        public static Index EMPLOYEES_PRIMARY = Internal.createIndex("PRIMARY", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.ID }, true);
        public static Index EMPLOYEES_STATE_PROVINCE = Internal.createIndex("state_province", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.STATE_PROVINCE }, false);
        public static Index EMPLOYEES_ZIP_POSTAL_CODE = Internal.createIndex("zip_postal_code", Employees.EMPLOYEES, new OrderField[] { Employees.EMPLOYEES.ZIP_POSTAL_CODE }, false);
        public static Index EMPLOYEE_PRIVILEGES_EMPLOYEE_ID = Internal.createIndex("employee_id", EmployeePrivileges.EMPLOYEE_PRIVILEGES, new OrderField[] { EmployeePrivileges.EMPLOYEE_PRIVILEGES.EMPLOYEE_ID }, false);
        public static Index EMPLOYEE_PRIVILEGES_PRIMARY = Internal.createIndex("PRIMARY", EmployeePrivileges.EMPLOYEE_PRIVILEGES, new OrderField[] { EmployeePrivileges.EMPLOYEE_PRIVILEGES.EMPLOYEE_ID, EmployeePrivileges.EMPLOYEE_PRIVILEGES.PRIVILEGE_ID }, true);
        public static Index EMPLOYEE_PRIVILEGES_PRIVILEGE_ID = Internal.createIndex("privilege_id", EmployeePrivileges.EMPLOYEE_PRIVILEGES, new OrderField[] { EmployeePrivileges.EMPLOYEE_PRIVILEGES.PRIVILEGE_ID }, false);
        public static Index EMPLOYEE_PRIVILEGES_PRIVILEGE_ID_2 = Internal.createIndex("privilege_id_2", EmployeePrivileges.EMPLOYEE_PRIVILEGES, new OrderField[] { EmployeePrivileges.EMPLOYEE_PRIVILEGES.PRIVILEGE_ID }, false);
        public static Index INVENTORY_TRANSACTIONS_CUSTOMER_ORDER_ID = Internal.createIndex("customer_order_id", InventoryTransactions.INVENTORY_TRANSACTIONS, new OrderField[] { InventoryTransactions.INVENTORY_TRANSACTIONS.CUSTOMER_ORDER_ID }, false);
        public static Index INVENTORY_TRANSACTIONS_CUSTOMER_ORDER_ID_2 = Internal.createIndex("customer_order_id_2", InventoryTransactions.INVENTORY_TRANSACTIONS, new OrderField[] { InventoryTransactions.INVENTORY_TRANSACTIONS.CUSTOMER_ORDER_ID }, false);
        public static Index INVENTORY_TRANSACTIONS_PRIMARY = Internal.createIndex("PRIMARY", InventoryTransactions.INVENTORY_TRANSACTIONS, new OrderField[] { InventoryTransactions.INVENTORY_TRANSACTIONS.ID }, true);
        public static Index INVENTORY_TRANSACTIONS_PRODUCT_ID = Internal.createIndex("product_id", InventoryTransactions.INVENTORY_TRANSACTIONS, new OrderField[] { InventoryTransactions.INVENTORY_TRANSACTIONS.PRODUCT_ID }, false);
        public static Index INVENTORY_TRANSACTIONS_PRODUCT_ID_2 = Internal.createIndex("product_id_2", InventoryTransactions.INVENTORY_TRANSACTIONS, new OrderField[] { InventoryTransactions.INVENTORY_TRANSACTIONS.PRODUCT_ID }, false);
        public static Index INVENTORY_TRANSACTIONS_PURCHASE_ORDER_ID = Internal.createIndex("purchase_order_id", InventoryTransactions.INVENTORY_TRANSACTIONS, new OrderField[] { InventoryTransactions.INVENTORY_TRANSACTIONS.PURCHASE_ORDER_ID }, false);
        public static Index INVENTORY_TRANSACTIONS_PURCHASE_ORDER_ID_2 = Internal.createIndex("purchase_order_id_2", InventoryTransactions.INVENTORY_TRANSACTIONS, new OrderField[] { InventoryTransactions.INVENTORY_TRANSACTIONS.PURCHASE_ORDER_ID }, false);
        public static Index INVENTORY_TRANSACTIONS_TRANSACTION_TYPE = Internal.createIndex("transaction_type", InventoryTransactions.INVENTORY_TRANSACTIONS, new OrderField[] { InventoryTransactions.INVENTORY_TRANSACTIONS.TRANSACTION_TYPE }, false);
        public static Index INVENTORY_TRANSACTION_TYPES_PRIMARY = Internal.createIndex("PRIMARY", InventoryTransactionTypes.INVENTORY_TRANSACTION_TYPES, new OrderField[] { InventoryTransactionTypes.INVENTORY_TRANSACTION_TYPES.ID }, true);
        public static Index INVOICES_FK_INVOICES_ORDERS1_IDX = Internal.createIndex("fk_invoices_orders1_idx", Invoices.INVOICES, new OrderField[] { Invoices.INVOICES.ORDER_ID }, false);
        public static Index INVOICES_ID = Internal.createIndex("id", Invoices.INVOICES, new OrderField[] { Invoices.INVOICES.ID }, false);
        public static Index INVOICES_ID_2 = Internal.createIndex("id_2", Invoices.INVOICES, new OrderField[] { Invoices.INVOICES.ID }, false);
        public static Index INVOICES_PRIMARY = Internal.createIndex("PRIMARY", Invoices.INVOICES, new OrderField[] { Invoices.INVOICES.ID }, true);
        public static Index ORDERS_CUSTOMER_ID = Internal.createIndex("customer_id", Orders.ORDERS, new OrderField[] { Orders.ORDERS.CUSTOMER_ID }, false);
        public static Index ORDERS_CUSTOMER_ID_2 = Internal.createIndex("customer_id_2", Orders.ORDERS, new OrderField[] { Orders.ORDERS.CUSTOMER_ID }, false);
        public static Index ORDERS_EMPLOYEE_ID = Internal.createIndex("employee_id", Orders.ORDERS, new OrderField[] { Orders.ORDERS.EMPLOYEE_ID }, false);
        public static Index ORDERS_EMPLOYEE_ID_2 = Internal.createIndex("employee_id_2", Orders.ORDERS, new OrderField[] { Orders.ORDERS.EMPLOYEE_ID }, false);
        public static Index ORDERS_FK_ORDERS_ORDERS_STATUS1 = Internal.createIndex("fk_orders_orders_status1", Orders.ORDERS, new OrderField[] { Orders.ORDERS.STATUS_ID }, false);
        public static Index ORDERS_ID = Internal.createIndex("id", Orders.ORDERS, new OrderField[] { Orders.ORDERS.ID }, false);
        public static Index ORDERS_ID_2 = Internal.createIndex("id_2", Orders.ORDERS, new OrderField[] { Orders.ORDERS.ID }, false);
        public static Index ORDERS_ID_3 = Internal.createIndex("id_3", Orders.ORDERS, new OrderField[] { Orders.ORDERS.ID }, false);
        public static Index ORDERS_PRIMARY = Internal.createIndex("PRIMARY", Orders.ORDERS, new OrderField[] { Orders.ORDERS.ID }, true);
        public static Index ORDERS_SHIPPER_ID = Internal.createIndex("shipper_id", Orders.ORDERS, new OrderField[] { Orders.ORDERS.SHIPPER_ID }, false);
        public static Index ORDERS_SHIPPER_ID_2 = Internal.createIndex("shipper_id_2", Orders.ORDERS, new OrderField[] { Orders.ORDERS.SHIPPER_ID }, false);
        public static Index ORDERS_SHIP_ZIP_POSTAL_CODE = Internal.createIndex("ship_zip_postal_code", Orders.ORDERS, new OrderField[] { Orders.ORDERS.SHIP_ZIP_POSTAL_CODE }, false);
        public static Index ORDERS_TAX_STATUS = Internal.createIndex("tax_status", Orders.ORDERS, new OrderField[] { Orders.ORDERS.TAX_STATUS_ID }, false);
        public static Index ORDERS_STATUS_PRIMARY = Internal.createIndex("PRIMARY", OrdersStatus.ORDERS_STATUS, new OrderField[] { OrdersStatus.ORDERS_STATUS.ID }, true);
        public static Index ORDERS_TAX_STATUS_PRIMARY = Internal.createIndex("PRIMARY", OrdersTaxStatus.ORDERS_TAX_STATUS, new OrderField[] { OrdersTaxStatus.ORDERS_TAX_STATUS.ID }, true);
        public static Index ORDER_DETAILS_FK_ORDER_DETAILS_ORDERS1_IDX = Internal.createIndex("fk_order_details_orders1_idx", OrderDetails.ORDER_DETAILS, new OrderField[] { OrderDetails.ORDER_DETAILS.ORDER_ID }, false);
        public static Index ORDER_DETAILS_FK_ORDER_DETAILS_ORDER_DETAILS_STATUS1_IDX = Internal.createIndex("fk_order_details_order_details_status1_idx", OrderDetails.ORDER_DETAILS, new OrderField[] { OrderDetails.ORDER_DETAILS.STATUS_ID }, false);
        public static Index ORDER_DETAILS_ID = Internal.createIndex("id", OrderDetails.ORDER_DETAILS, new OrderField[] { OrderDetails.ORDER_DETAILS.ID }, false);
        public static Index ORDER_DETAILS_ID_2 = Internal.createIndex("id_2", OrderDetails.ORDER_DETAILS, new OrderField[] { OrderDetails.ORDER_DETAILS.ID }, false);
        public static Index ORDER_DETAILS_ID_3 = Internal.createIndex("id_3", OrderDetails.ORDER_DETAILS, new OrderField[] { OrderDetails.ORDER_DETAILS.ID }, false);
        public static Index ORDER_DETAILS_ID_4 = Internal.createIndex("id_4", OrderDetails.ORDER_DETAILS, new OrderField[] { OrderDetails.ORDER_DETAILS.ID }, false);
        public static Index ORDER_DETAILS_ID_5 = Internal.createIndex("id_5", OrderDetails.ORDER_DETAILS, new OrderField[] { OrderDetails.ORDER_DETAILS.ID }, false);
        public static Index ORDER_DETAILS_INVENTORY_ID = Internal.createIndex("inventory_id", OrderDetails.ORDER_DETAILS, new OrderField[] { OrderDetails.ORDER_DETAILS.INVENTORY_ID }, false);
        public static Index ORDER_DETAILS_PRIMARY = Internal.createIndex("PRIMARY", OrderDetails.ORDER_DETAILS, new OrderField[] { OrderDetails.ORDER_DETAILS.ID }, true);
        public static Index ORDER_DETAILS_PRODUCT_ID = Internal.createIndex("product_id", OrderDetails.ORDER_DETAILS, new OrderField[] { OrderDetails.ORDER_DETAILS.PRODUCT_ID }, false);
        public static Index ORDER_DETAILS_PRODUCT_ID_2 = Internal.createIndex("product_id_2", OrderDetails.ORDER_DETAILS, new OrderField[] { OrderDetails.ORDER_DETAILS.PRODUCT_ID }, false);
        public static Index ORDER_DETAILS_PURCHASE_ORDER_ID = Internal.createIndex("purchase_order_id", OrderDetails.ORDER_DETAILS, new OrderField[] { OrderDetails.ORDER_DETAILS.PURCHASE_ORDER_ID }, false);
        public static Index ORDER_DETAILS_STATUS_PRIMARY = Internal.createIndex("PRIMARY", OrderDetailsStatus.ORDER_DETAILS_STATUS, new OrderField[] { OrderDetailsStatus.ORDER_DETAILS_STATUS.ID }, true);
        public static Index PRIVILEGES_PRIMARY = Internal.createIndex("PRIMARY", Privileges.PRIVILEGES, new OrderField[] { Privileges.PRIVILEGES.ID }, true);
        public static Index PRODUCTS_PRIMARY = Internal.createIndex("PRIMARY", Products.PRODUCTS, new OrderField[] { Products.PRODUCTS.ID }, true);
        public static Index PRODUCTS_PRODUCT_CODE = Internal.createIndex("product_code", Products.PRODUCTS, new OrderField[] { Products.PRODUCTS.PRODUCT_CODE }, false);
        public static Index PURCHASE_ORDERS_CREATED_BY = Internal.createIndex("created_by", PurchaseOrders.PURCHASE_ORDERS, new OrderField[] { PurchaseOrders.PURCHASE_ORDERS.CREATED_BY }, false);
        public static Index PURCHASE_ORDERS_ID = Internal.createIndex("id", PurchaseOrders.PURCHASE_ORDERS, new OrderField[] { PurchaseOrders.PURCHASE_ORDERS.ID }, true);
        public static Index PURCHASE_ORDERS_ID_2 = Internal.createIndex("id_2", PurchaseOrders.PURCHASE_ORDERS, new OrderField[] { PurchaseOrders.PURCHASE_ORDERS.ID }, false);
        public static Index PURCHASE_ORDERS_PRIMARY = Internal.createIndex("PRIMARY", PurchaseOrders.PURCHASE_ORDERS, new OrderField[] { PurchaseOrders.PURCHASE_ORDERS.ID }, true);
        public static Index PURCHASE_ORDERS_STATUS_ID = Internal.createIndex("status_id", PurchaseOrders.PURCHASE_ORDERS, new OrderField[] { PurchaseOrders.PURCHASE_ORDERS.STATUS_ID }, false);
        public static Index PURCHASE_ORDERS_SUPPLIER_ID = Internal.createIndex("supplier_id", PurchaseOrders.PURCHASE_ORDERS, new OrderField[] { PurchaseOrders.PURCHASE_ORDERS.SUPPLIER_ID }, false);
        public static Index PURCHASE_ORDERS_SUPPLIER_ID_2 = Internal.createIndex("supplier_id_2", PurchaseOrders.PURCHASE_ORDERS, new OrderField[] { PurchaseOrders.PURCHASE_ORDERS.SUPPLIER_ID }, false);
        public static Index PURCHASE_ORDER_DETAILS_ID = Internal.createIndex("id", PurchaseOrderDetails.PURCHASE_ORDER_DETAILS, new OrderField[] { PurchaseOrderDetails.PURCHASE_ORDER_DETAILS.ID }, false);
        public static Index PURCHASE_ORDER_DETAILS_INVENTORY_ID = Internal.createIndex("inventory_id", PurchaseOrderDetails.PURCHASE_ORDER_DETAILS, new OrderField[] { PurchaseOrderDetails.PURCHASE_ORDER_DETAILS.INVENTORY_ID }, false);
        public static Index PURCHASE_ORDER_DETAILS_INVENTORY_ID_2 = Internal.createIndex("inventory_id_2", PurchaseOrderDetails.PURCHASE_ORDER_DETAILS, new OrderField[] { PurchaseOrderDetails.PURCHASE_ORDER_DETAILS.INVENTORY_ID }, false);
        public static Index PURCHASE_ORDER_DETAILS_PRIMARY = Internal.createIndex("PRIMARY", PurchaseOrderDetails.PURCHASE_ORDER_DETAILS, new OrderField[] { PurchaseOrderDetails.PURCHASE_ORDER_DETAILS.ID }, true);
        public static Index PURCHASE_ORDER_DETAILS_PRODUCT_ID = Internal.createIndex("product_id", PurchaseOrderDetails.PURCHASE_ORDER_DETAILS, new OrderField[] { PurchaseOrderDetails.PURCHASE_ORDER_DETAILS.PRODUCT_ID }, false);
        public static Index PURCHASE_ORDER_DETAILS_PRODUCT_ID_2 = Internal.createIndex("product_id_2", PurchaseOrderDetails.PURCHASE_ORDER_DETAILS, new OrderField[] { PurchaseOrderDetails.PURCHASE_ORDER_DETAILS.PRODUCT_ID }, false);
        public static Index PURCHASE_ORDER_DETAILS_PURCHASE_ORDER_ID = Internal.createIndex("purchase_order_id", PurchaseOrderDetails.PURCHASE_ORDER_DETAILS, new OrderField[] { PurchaseOrderDetails.PURCHASE_ORDER_DETAILS.PURCHASE_ORDER_ID }, false);
        public static Index PURCHASE_ORDER_DETAILS_PURCHASE_ORDER_ID_2 = Internal.createIndex("purchase_order_id_2", PurchaseOrderDetails.PURCHASE_ORDER_DETAILS, new OrderField[] { PurchaseOrderDetails.PURCHASE_ORDER_DETAILS.PURCHASE_ORDER_ID }, false);
        public static Index PURCHASE_ORDER_STATUS_PRIMARY = Internal.createIndex("PRIMARY", PurchaseOrderStatus.PURCHASE_ORDER_STATUS, new OrderField[] { PurchaseOrderStatus.PURCHASE_ORDER_STATUS.ID }, true);
        public static Index SALES_REPORTS_PRIMARY = Internal.createIndex("PRIMARY", SalesReports.SALES_REPORTS, new OrderField[] { SalesReports.SALES_REPORTS.GROUP_BY }, true);
        public static Index SHIPPERS_CITY = Internal.createIndex("city", Shippers.SHIPPERS, new OrderField[] { Shippers.SHIPPERS.CITY }, false);
        public static Index SHIPPERS_COMPANY = Internal.createIndex("company", Shippers.SHIPPERS, new OrderField[] { Shippers.SHIPPERS.COMPANY }, false);
        public static Index SHIPPERS_FIRST_NAME = Internal.createIndex("first_name", Shippers.SHIPPERS, new OrderField[] { Shippers.SHIPPERS.FIRST_NAME }, false);
        public static Index SHIPPERS_LAST_NAME = Internal.createIndex("last_name", Shippers.SHIPPERS, new OrderField[] { Shippers.SHIPPERS.LAST_NAME }, false);
        public static Index SHIPPERS_PRIMARY = Internal.createIndex("PRIMARY", Shippers.SHIPPERS, new OrderField[] { Shippers.SHIPPERS.ID }, true);
        public static Index SHIPPERS_STATE_PROVINCE = Internal.createIndex("state_province", Shippers.SHIPPERS, new OrderField[] { Shippers.SHIPPERS.STATE_PROVINCE }, false);
        public static Index SHIPPERS_ZIP_POSTAL_CODE = Internal.createIndex("zip_postal_code", Shippers.SHIPPERS, new OrderField[] { Shippers.SHIPPERS.ZIP_POSTAL_CODE }, false);
        public static Index STRINGS_PRIMARY = Internal.createIndex("PRIMARY", Strings.STRINGS, new OrderField[] { Strings.STRINGS.STRING_ID }, true);
        public static Index SUPPLIERS_CITY = Internal.createIndex("city", Suppliers.SUPPLIERS, new OrderField[] { Suppliers.SUPPLIERS.CITY }, false);
        public static Index SUPPLIERS_COMPANY = Internal.createIndex("company", Suppliers.SUPPLIERS, new OrderField[] { Suppliers.SUPPLIERS.COMPANY }, false);
        public static Index SUPPLIERS_FIRST_NAME = Internal.createIndex("first_name", Suppliers.SUPPLIERS, new OrderField[] { Suppliers.SUPPLIERS.FIRST_NAME }, false);
        public static Index SUPPLIERS_LAST_NAME = Internal.createIndex("last_name", Suppliers.SUPPLIERS, new OrderField[] { Suppliers.SUPPLIERS.LAST_NAME }, false);
        public static Index SUPPLIERS_PRIMARY = Internal.createIndex("PRIMARY", Suppliers.SUPPLIERS, new OrderField[] { Suppliers.SUPPLIERS.ID }, true);
        public static Index SUPPLIERS_STATE_PROVINCE = Internal.createIndex("state_province", Suppliers.SUPPLIERS, new OrderField[] { Suppliers.SUPPLIERS.STATE_PROVINCE }, false);
        public static Index SUPPLIERS_ZIP_POSTAL_CODE = Internal.createIndex("zip_postal_code", Suppliers.SUPPLIERS, new OrderField[] { Suppliers.SUPPLIERS.ZIP_POSTAL_CODE }, false);
    }
}
