/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain;


import com.jooq.example.domain.tables.Customers;
import com.jooq.example.domain.tables.EmployeePrivileges;
import com.jooq.example.domain.tables.Employees;
import com.jooq.example.domain.tables.InventoryTransactionTypes;
import com.jooq.example.domain.tables.InventoryTransactions;
import com.jooq.example.domain.tables.Invoices;
import com.jooq.example.domain.tables.OrderDetails;
import com.jooq.example.domain.tables.OrderDetailsStatus;
import com.jooq.example.domain.tables.Orders;
import com.jooq.example.domain.tables.OrdersStatus;
import com.jooq.example.domain.tables.OrdersTaxStatus;
import com.jooq.example.domain.tables.Privileges;
import com.jooq.example.domain.tables.Products;
import com.jooq.example.domain.tables.PurchaseOrderDetails;
import com.jooq.example.domain.tables.PurchaseOrderStatus;
import com.jooq.example.domain.tables.PurchaseOrders;
import com.jooq.example.domain.tables.SalesReports;
import com.jooq.example.domain.tables.Shippers;
import com.jooq.example.domain.tables.Strings;
import com.jooq.example.domain.tables.Suppliers;
import com.jooq.example.domain.tables.records.CustomersRecord;
import com.jooq.example.domain.tables.records.EmployeePrivilegesRecord;
import com.jooq.example.domain.tables.records.EmployeesRecord;
import com.jooq.example.domain.tables.records.InventoryTransactionTypesRecord;
import com.jooq.example.domain.tables.records.InventoryTransactionsRecord;
import com.jooq.example.domain.tables.records.InvoicesRecord;
import com.jooq.example.domain.tables.records.OrderDetailsRecord;
import com.jooq.example.domain.tables.records.OrderDetailsStatusRecord;
import com.jooq.example.domain.tables.records.OrdersRecord;
import com.jooq.example.domain.tables.records.OrdersStatusRecord;
import com.jooq.example.domain.tables.records.OrdersTaxStatusRecord;
import com.jooq.example.domain.tables.records.PrivilegesRecord;
import com.jooq.example.domain.tables.records.ProductsRecord;
import com.jooq.example.domain.tables.records.PurchaseOrderDetailsRecord;
import com.jooq.example.domain.tables.records.PurchaseOrderStatusRecord;
import com.jooq.example.domain.tables.records.PurchaseOrdersRecord;
import com.jooq.example.domain.tables.records.SalesReportsRecord;
import com.jooq.example.domain.tables.records.ShippersRecord;
import com.jooq.example.domain.tables.records.StringsRecord;
import com.jooq.example.domain.tables.records.SuppliersRecord;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>northwind</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CustomersRecord, Integer> IDENTITY_CUSTOMERS = Identities0.IDENTITY_CUSTOMERS;
    public static final Identity<EmployeesRecord, Integer> IDENTITY_EMPLOYEES = Identities0.IDENTITY_EMPLOYEES;
    public static final Identity<InventoryTransactionsRecord, Integer> IDENTITY_INVENTORY_TRANSACTIONS = Identities0.IDENTITY_INVENTORY_TRANSACTIONS;
    public static final Identity<InvoicesRecord, Integer> IDENTITY_INVOICES = Identities0.IDENTITY_INVOICES;
    public static final Identity<OrdersRecord, Integer> IDENTITY_ORDERS = Identities0.IDENTITY_ORDERS;
    public static final Identity<OrderDetailsRecord, Integer> IDENTITY_ORDER_DETAILS = Identities0.IDENTITY_ORDER_DETAILS;
    public static final Identity<PrivilegesRecord, Integer> IDENTITY_PRIVILEGES = Identities0.IDENTITY_PRIVILEGES;
    public static final Identity<ProductsRecord, Integer> IDENTITY_PRODUCTS = Identities0.IDENTITY_PRODUCTS;
    public static final Identity<PurchaseOrdersRecord, Integer> IDENTITY_PURCHASE_ORDERS = Identities0.IDENTITY_PURCHASE_ORDERS;
    public static final Identity<PurchaseOrderDetailsRecord, Integer> IDENTITY_PURCHASE_ORDER_DETAILS = Identities0.IDENTITY_PURCHASE_ORDER_DETAILS;
    public static final Identity<ShippersRecord, Integer> IDENTITY_SHIPPERS = Identities0.IDENTITY_SHIPPERS;
    public static final Identity<StringsRecord, Integer> IDENTITY_STRINGS = Identities0.IDENTITY_STRINGS;
    public static final Identity<SuppliersRecord, Integer> IDENTITY_SUPPLIERS = Identities0.IDENTITY_SUPPLIERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomersRecord> KEY_CUSTOMERS_PRIMARY = UniqueKeys0.KEY_CUSTOMERS_PRIMARY;
    public static final UniqueKey<EmployeesRecord> KEY_EMPLOYEES_PRIMARY = UniqueKeys0.KEY_EMPLOYEES_PRIMARY;
    public static final UniqueKey<EmployeePrivilegesRecord> KEY_EMPLOYEE_PRIVILEGES_PRIMARY = UniqueKeys0.KEY_EMPLOYEE_PRIVILEGES_PRIMARY;
    public static final UniqueKey<InventoryTransactionsRecord> KEY_INVENTORY_TRANSACTIONS_PRIMARY = UniqueKeys0.KEY_INVENTORY_TRANSACTIONS_PRIMARY;
    public static final UniqueKey<InventoryTransactionTypesRecord> KEY_INVENTORY_TRANSACTION_TYPES_PRIMARY = UniqueKeys0.KEY_INVENTORY_TRANSACTION_TYPES_PRIMARY;
    public static final UniqueKey<InvoicesRecord> KEY_INVOICES_PRIMARY = UniqueKeys0.KEY_INVOICES_PRIMARY;
    public static final UniqueKey<OrdersRecord> KEY_ORDERS_PRIMARY = UniqueKeys0.KEY_ORDERS_PRIMARY;
    public static final UniqueKey<OrdersStatusRecord> KEY_ORDERS_STATUS_PRIMARY = UniqueKeys0.KEY_ORDERS_STATUS_PRIMARY;
    public static final UniqueKey<OrdersTaxStatusRecord> KEY_ORDERS_TAX_STATUS_PRIMARY = UniqueKeys0.KEY_ORDERS_TAX_STATUS_PRIMARY;
    public static final UniqueKey<OrderDetailsRecord> KEY_ORDER_DETAILS_PRIMARY = UniqueKeys0.KEY_ORDER_DETAILS_PRIMARY;
    public static final UniqueKey<OrderDetailsStatusRecord> KEY_ORDER_DETAILS_STATUS_PRIMARY = UniqueKeys0.KEY_ORDER_DETAILS_STATUS_PRIMARY;
    public static final UniqueKey<PrivilegesRecord> KEY_PRIVILEGES_PRIMARY = UniqueKeys0.KEY_PRIVILEGES_PRIMARY;
    public static final UniqueKey<ProductsRecord> KEY_PRODUCTS_PRIMARY = UniqueKeys0.KEY_PRODUCTS_PRIMARY;
    public static final UniqueKey<PurchaseOrdersRecord> KEY_PURCHASE_ORDERS_PRIMARY = UniqueKeys0.KEY_PURCHASE_ORDERS_PRIMARY;
    public static final UniqueKey<PurchaseOrdersRecord> KEY_PURCHASE_ORDERS_ID = UniqueKeys0.KEY_PURCHASE_ORDERS_ID;
    public static final UniqueKey<PurchaseOrderDetailsRecord> KEY_PURCHASE_ORDER_DETAILS_PRIMARY = UniqueKeys0.KEY_PURCHASE_ORDER_DETAILS_PRIMARY;
    public static final UniqueKey<PurchaseOrderStatusRecord> KEY_PURCHASE_ORDER_STATUS_PRIMARY = UniqueKeys0.KEY_PURCHASE_ORDER_STATUS_PRIMARY;
    public static final UniqueKey<SalesReportsRecord> KEY_SALES_REPORTS_PRIMARY = UniqueKeys0.KEY_SALES_REPORTS_PRIMARY;
    public static final UniqueKey<ShippersRecord> KEY_SHIPPERS_PRIMARY = UniqueKeys0.KEY_SHIPPERS_PRIMARY;
    public static final UniqueKey<StringsRecord> KEY_STRINGS_PRIMARY = UniqueKeys0.KEY_STRINGS_PRIMARY;
    public static final UniqueKey<SuppliersRecord> KEY_SUPPLIERS_PRIMARY = UniqueKeys0.KEY_SUPPLIERS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<EmployeePrivilegesRecord, EmployeesRecord> FK_EMPLOYEE_PRIVILEGES_EMPLOYEES1 = ForeignKeys0.FK_EMPLOYEE_PRIVILEGES_EMPLOYEES1;
    public static final ForeignKey<EmployeePrivilegesRecord, PrivilegesRecord> FK_EMPLOYEE_PRIVILEGES_PRIVILEGES1 = ForeignKeys0.FK_EMPLOYEE_PRIVILEGES_PRIVILEGES1;
    public static final ForeignKey<InventoryTransactionsRecord, InventoryTransactionTypesRecord> FK_INVENTORY_TRANSACTIONS_INVENTORY_TRANSACTION_TYPES1 = ForeignKeys0.FK_INVENTORY_TRANSACTIONS_INVENTORY_TRANSACTION_TYPES1;
    public static final ForeignKey<InventoryTransactionsRecord, ProductsRecord> FK_INVENTORY_TRANSACTIONS_PRODUCTS1 = ForeignKeys0.FK_INVENTORY_TRANSACTIONS_PRODUCTS1;
    public static final ForeignKey<InventoryTransactionsRecord, PurchaseOrdersRecord> FK_INVENTORY_TRANSACTIONS_PURCHASE_ORDERS1 = ForeignKeys0.FK_INVENTORY_TRANSACTIONS_PURCHASE_ORDERS1;
    public static final ForeignKey<InventoryTransactionsRecord, OrdersRecord> FK_INVENTORY_TRANSACTIONS_ORDERS1 = ForeignKeys0.FK_INVENTORY_TRANSACTIONS_ORDERS1;
    public static final ForeignKey<InvoicesRecord, OrdersRecord> FK_INVOICES_ORDERS1 = ForeignKeys0.FK_INVOICES_ORDERS1;
    public static final ForeignKey<OrdersRecord, EmployeesRecord> FK_ORDERS_EMPLOYEES1 = ForeignKeys0.FK_ORDERS_EMPLOYEES1;
    public static final ForeignKey<OrdersRecord, CustomersRecord> FK_ORDERS_CUSTOMERS = ForeignKeys0.FK_ORDERS_CUSTOMERS;
    public static final ForeignKey<OrdersRecord, ShippersRecord> FK_ORDERS_SHIPPERS1 = ForeignKeys0.FK_ORDERS_SHIPPERS1;
    public static final ForeignKey<OrdersRecord, OrdersTaxStatusRecord> FK_ORDERS_ORDERS_TAX_STATUS1 = ForeignKeys0.FK_ORDERS_ORDERS_TAX_STATUS1;
    public static final ForeignKey<OrdersRecord, OrdersStatusRecord> FK_ORDERS_ORDERS_STATUS1 = ForeignKeys0.FK_ORDERS_ORDERS_STATUS1;
    public static final ForeignKey<OrderDetailsRecord, OrdersRecord> FK_ORDER_DETAILS_ORDERS1 = ForeignKeys0.FK_ORDER_DETAILS_ORDERS1;
    public static final ForeignKey<OrderDetailsRecord, ProductsRecord> FK_ORDER_DETAILS_PRODUCTS1 = ForeignKeys0.FK_ORDER_DETAILS_PRODUCTS1;
    public static final ForeignKey<OrderDetailsRecord, OrderDetailsStatusRecord> FK_ORDER_DETAILS_ORDER_DETAILS_STATUS1 = ForeignKeys0.FK_ORDER_DETAILS_ORDER_DETAILS_STATUS1;
    public static final ForeignKey<PurchaseOrdersRecord, SuppliersRecord> FK_PURCHASE_ORDERS_SUPPLIERS1 = ForeignKeys0.FK_PURCHASE_ORDERS_SUPPLIERS1;
    public static final ForeignKey<PurchaseOrdersRecord, EmployeesRecord> FK_PURCHASE_ORDERS_EMPLOYEES1 = ForeignKeys0.FK_PURCHASE_ORDERS_EMPLOYEES1;
    public static final ForeignKey<PurchaseOrdersRecord, PurchaseOrderStatusRecord> FK_PURCHASE_ORDERS_PURCHASE_ORDER_STATUS1 = ForeignKeys0.FK_PURCHASE_ORDERS_PURCHASE_ORDER_STATUS1;
    public static final ForeignKey<PurchaseOrderDetailsRecord, PurchaseOrdersRecord> FK_PURCHASE_ORDER_DETAILS_PURCHASE_ORDERS1 = ForeignKeys0.FK_PURCHASE_ORDER_DETAILS_PURCHASE_ORDERS1;
    public static final ForeignKey<PurchaseOrderDetailsRecord, ProductsRecord> FK_PURCHASE_ORDER_DETAILS_PRODUCTS1 = ForeignKeys0.FK_PURCHASE_ORDER_DETAILS_PRODUCTS1;
    public static final ForeignKey<PurchaseOrderDetailsRecord, InventoryTransactionsRecord> FK_PURCHASE_ORDER_DETAILS_INVENTORY_TRANSACTIONS1 = ForeignKeys0.FK_PURCHASE_ORDER_DETAILS_INVENTORY_TRANSACTIONS1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CustomersRecord, Integer> IDENTITY_CUSTOMERS = Internal.createIdentity(Customers.CUSTOMERS, Customers.CUSTOMERS.ID);
        public static Identity<EmployeesRecord, Integer> IDENTITY_EMPLOYEES = Internal.createIdentity(Employees.EMPLOYEES, Employees.EMPLOYEES.ID);
        public static Identity<InventoryTransactionsRecord, Integer> IDENTITY_INVENTORY_TRANSACTIONS = Internal.createIdentity(InventoryTransactions.INVENTORY_TRANSACTIONS, InventoryTransactions.INVENTORY_TRANSACTIONS.ID);
        public static Identity<InvoicesRecord, Integer> IDENTITY_INVOICES = Internal.createIdentity(Invoices.INVOICES, Invoices.INVOICES.ID);
        public static Identity<OrdersRecord, Integer> IDENTITY_ORDERS = Internal.createIdentity(Orders.ORDERS, Orders.ORDERS.ID);
        public static Identity<OrderDetailsRecord, Integer> IDENTITY_ORDER_DETAILS = Internal.createIdentity(OrderDetails.ORDER_DETAILS, OrderDetails.ORDER_DETAILS.ID);
        public static Identity<PrivilegesRecord, Integer> IDENTITY_PRIVILEGES = Internal.createIdentity(Privileges.PRIVILEGES, Privileges.PRIVILEGES.ID);
        public static Identity<ProductsRecord, Integer> IDENTITY_PRODUCTS = Internal.createIdentity(Products.PRODUCTS, Products.PRODUCTS.ID);
        public static Identity<PurchaseOrdersRecord, Integer> IDENTITY_PURCHASE_ORDERS = Internal.createIdentity(PurchaseOrders.PURCHASE_ORDERS, PurchaseOrders.PURCHASE_ORDERS.ID);
        public static Identity<PurchaseOrderDetailsRecord, Integer> IDENTITY_PURCHASE_ORDER_DETAILS = Internal.createIdentity(PurchaseOrderDetails.PURCHASE_ORDER_DETAILS, PurchaseOrderDetails.PURCHASE_ORDER_DETAILS.ID);
        public static Identity<ShippersRecord, Integer> IDENTITY_SHIPPERS = Internal.createIdentity(Shippers.SHIPPERS, Shippers.SHIPPERS.ID);
        public static Identity<StringsRecord, Integer> IDENTITY_STRINGS = Internal.createIdentity(Strings.STRINGS, Strings.STRINGS.STRING_ID);
        public static Identity<SuppliersRecord, Integer> IDENTITY_SUPPLIERS = Internal.createIdentity(Suppliers.SUPPLIERS, Suppliers.SUPPLIERS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CustomersRecord> KEY_CUSTOMERS_PRIMARY = Internal.createUniqueKey(Customers.CUSTOMERS, "KEY_customers_PRIMARY", Customers.CUSTOMERS.ID);
        public static final UniqueKey<EmployeesRecord> KEY_EMPLOYEES_PRIMARY = Internal.createUniqueKey(Employees.EMPLOYEES, "KEY_employees_PRIMARY", Employees.EMPLOYEES.ID);
        public static final UniqueKey<EmployeePrivilegesRecord> KEY_EMPLOYEE_PRIVILEGES_PRIMARY = Internal.createUniqueKey(EmployeePrivileges.EMPLOYEE_PRIVILEGES, "KEY_employee_privileges_PRIMARY", EmployeePrivileges.EMPLOYEE_PRIVILEGES.EMPLOYEE_ID, EmployeePrivileges.EMPLOYEE_PRIVILEGES.PRIVILEGE_ID);
        public static final UniqueKey<InventoryTransactionsRecord> KEY_INVENTORY_TRANSACTIONS_PRIMARY = Internal.createUniqueKey(InventoryTransactions.INVENTORY_TRANSACTIONS, "KEY_inventory_transactions_PRIMARY", InventoryTransactions.INVENTORY_TRANSACTIONS.ID);
        public static final UniqueKey<InventoryTransactionTypesRecord> KEY_INVENTORY_TRANSACTION_TYPES_PRIMARY = Internal.createUniqueKey(InventoryTransactionTypes.INVENTORY_TRANSACTION_TYPES, "KEY_inventory_transaction_types_PRIMARY", InventoryTransactionTypes.INVENTORY_TRANSACTION_TYPES.ID);
        public static final UniqueKey<InvoicesRecord> KEY_INVOICES_PRIMARY = Internal.createUniqueKey(Invoices.INVOICES, "KEY_invoices_PRIMARY", Invoices.INVOICES.ID);
        public static final UniqueKey<OrdersRecord> KEY_ORDERS_PRIMARY = Internal.createUniqueKey(Orders.ORDERS, "KEY_orders_PRIMARY", Orders.ORDERS.ID);
        public static final UniqueKey<OrdersStatusRecord> KEY_ORDERS_STATUS_PRIMARY = Internal.createUniqueKey(OrdersStatus.ORDERS_STATUS, "KEY_orders_status_PRIMARY", OrdersStatus.ORDERS_STATUS.ID);
        public static final UniqueKey<OrdersTaxStatusRecord> KEY_ORDERS_TAX_STATUS_PRIMARY = Internal.createUniqueKey(OrdersTaxStatus.ORDERS_TAX_STATUS, "KEY_orders_tax_status_PRIMARY", OrdersTaxStatus.ORDERS_TAX_STATUS.ID);
        public static final UniqueKey<OrderDetailsRecord> KEY_ORDER_DETAILS_PRIMARY = Internal.createUniqueKey(OrderDetails.ORDER_DETAILS, "KEY_order_details_PRIMARY", OrderDetails.ORDER_DETAILS.ID);
        public static final UniqueKey<OrderDetailsStatusRecord> KEY_ORDER_DETAILS_STATUS_PRIMARY = Internal.createUniqueKey(OrderDetailsStatus.ORDER_DETAILS_STATUS, "KEY_order_details_status_PRIMARY", OrderDetailsStatus.ORDER_DETAILS_STATUS.ID);
        public static final UniqueKey<PrivilegesRecord> KEY_PRIVILEGES_PRIMARY = Internal.createUniqueKey(Privileges.PRIVILEGES, "KEY_privileges_PRIMARY", Privileges.PRIVILEGES.ID);
        public static final UniqueKey<ProductsRecord> KEY_PRODUCTS_PRIMARY = Internal.createUniqueKey(Products.PRODUCTS, "KEY_products_PRIMARY", Products.PRODUCTS.ID);
        public static final UniqueKey<PurchaseOrdersRecord> KEY_PURCHASE_ORDERS_PRIMARY = Internal.createUniqueKey(PurchaseOrders.PURCHASE_ORDERS, "KEY_purchase_orders_PRIMARY", PurchaseOrders.PURCHASE_ORDERS.ID);
        public static final UniqueKey<PurchaseOrdersRecord> KEY_PURCHASE_ORDERS_ID = Internal.createUniqueKey(PurchaseOrders.PURCHASE_ORDERS, "KEY_purchase_orders_id", PurchaseOrders.PURCHASE_ORDERS.ID);
        public static final UniqueKey<PurchaseOrderDetailsRecord> KEY_PURCHASE_ORDER_DETAILS_PRIMARY = Internal.createUniqueKey(PurchaseOrderDetails.PURCHASE_ORDER_DETAILS, "KEY_purchase_order_details_PRIMARY", PurchaseOrderDetails.PURCHASE_ORDER_DETAILS.ID);
        public static final UniqueKey<PurchaseOrderStatusRecord> KEY_PURCHASE_ORDER_STATUS_PRIMARY = Internal.createUniqueKey(PurchaseOrderStatus.PURCHASE_ORDER_STATUS, "KEY_purchase_order_status_PRIMARY", PurchaseOrderStatus.PURCHASE_ORDER_STATUS.ID);
        public static final UniqueKey<SalesReportsRecord> KEY_SALES_REPORTS_PRIMARY = Internal.createUniqueKey(SalesReports.SALES_REPORTS, "KEY_sales_reports_PRIMARY", SalesReports.SALES_REPORTS.GROUP_BY);
        public static final UniqueKey<ShippersRecord> KEY_SHIPPERS_PRIMARY = Internal.createUniqueKey(Shippers.SHIPPERS, "KEY_shippers_PRIMARY", Shippers.SHIPPERS.ID);
        public static final UniqueKey<StringsRecord> KEY_STRINGS_PRIMARY = Internal.createUniqueKey(Strings.STRINGS, "KEY_strings_PRIMARY", Strings.STRINGS.STRING_ID);
        public static final UniqueKey<SuppliersRecord> KEY_SUPPLIERS_PRIMARY = Internal.createUniqueKey(Suppliers.SUPPLIERS, "KEY_suppliers_PRIMARY", Suppliers.SUPPLIERS.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<EmployeePrivilegesRecord, EmployeesRecord> FK_EMPLOYEE_PRIVILEGES_EMPLOYEES1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_EMPLOYEES_PRIMARY, EmployeePrivileges.EMPLOYEE_PRIVILEGES, "fk_employee_privileges_employees1", EmployeePrivileges.EMPLOYEE_PRIVILEGES.EMPLOYEE_ID);
        public static final ForeignKey<EmployeePrivilegesRecord, PrivilegesRecord> FK_EMPLOYEE_PRIVILEGES_PRIVILEGES1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_PRIVILEGES_PRIMARY, EmployeePrivileges.EMPLOYEE_PRIVILEGES, "fk_employee_privileges_privileges1", EmployeePrivileges.EMPLOYEE_PRIVILEGES.PRIVILEGE_ID);
        public static final ForeignKey<InventoryTransactionsRecord, InventoryTransactionTypesRecord> FK_INVENTORY_TRANSACTIONS_INVENTORY_TRANSACTION_TYPES1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_INVENTORY_TRANSACTION_TYPES_PRIMARY, InventoryTransactions.INVENTORY_TRANSACTIONS, "fk_inventory_transactions_inventory_transaction_types1", InventoryTransactions.INVENTORY_TRANSACTIONS.TRANSACTION_TYPE);
        public static final ForeignKey<InventoryTransactionsRecord, ProductsRecord> FK_INVENTORY_TRANSACTIONS_PRODUCTS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_PRODUCTS_PRIMARY, InventoryTransactions.INVENTORY_TRANSACTIONS, "fk_inventory_transactions_products1", InventoryTransactions.INVENTORY_TRANSACTIONS.PRODUCT_ID);
        public static final ForeignKey<InventoryTransactionsRecord, PurchaseOrdersRecord> FK_INVENTORY_TRANSACTIONS_PURCHASE_ORDERS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_PURCHASE_ORDERS_PRIMARY, InventoryTransactions.INVENTORY_TRANSACTIONS, "fk_inventory_transactions_purchase_orders1", InventoryTransactions.INVENTORY_TRANSACTIONS.PURCHASE_ORDER_ID);
        public static final ForeignKey<InventoryTransactionsRecord, OrdersRecord> FK_INVENTORY_TRANSACTIONS_ORDERS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_ORDERS_PRIMARY, InventoryTransactions.INVENTORY_TRANSACTIONS, "fk_inventory_transactions_orders1", InventoryTransactions.INVENTORY_TRANSACTIONS.CUSTOMER_ORDER_ID);
        public static final ForeignKey<InvoicesRecord, OrdersRecord> FK_INVOICES_ORDERS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_ORDERS_PRIMARY, Invoices.INVOICES, "fk_invoices_orders1", Invoices.INVOICES.ORDER_ID);
        public static final ForeignKey<OrdersRecord, EmployeesRecord> FK_ORDERS_EMPLOYEES1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_EMPLOYEES_PRIMARY, Orders.ORDERS, "fk_orders_employees1", Orders.ORDERS.EMPLOYEE_ID);
        public static final ForeignKey<OrdersRecord, CustomersRecord> FK_ORDERS_CUSTOMERS = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_CUSTOMERS_PRIMARY, Orders.ORDERS, "fk_orders_customers", Orders.ORDERS.CUSTOMER_ID);
        public static final ForeignKey<OrdersRecord, ShippersRecord> FK_ORDERS_SHIPPERS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_SHIPPERS_PRIMARY, Orders.ORDERS, "fk_orders_shippers1", Orders.ORDERS.SHIPPER_ID);
        public static final ForeignKey<OrdersRecord, OrdersTaxStatusRecord> FK_ORDERS_ORDERS_TAX_STATUS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_ORDERS_TAX_STATUS_PRIMARY, Orders.ORDERS, "fk_orders_orders_tax_status1", Orders.ORDERS.TAX_STATUS_ID);
        public static final ForeignKey<OrdersRecord, OrdersStatusRecord> FK_ORDERS_ORDERS_STATUS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_ORDERS_STATUS_PRIMARY, Orders.ORDERS, "fk_orders_orders_status1", Orders.ORDERS.STATUS_ID);
        public static final ForeignKey<OrderDetailsRecord, OrdersRecord> FK_ORDER_DETAILS_ORDERS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_ORDERS_PRIMARY, OrderDetails.ORDER_DETAILS, "fk_order_details_orders1", OrderDetails.ORDER_DETAILS.ORDER_ID);
        public static final ForeignKey<OrderDetailsRecord, ProductsRecord> FK_ORDER_DETAILS_PRODUCTS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_PRODUCTS_PRIMARY, OrderDetails.ORDER_DETAILS, "fk_order_details_products1", OrderDetails.ORDER_DETAILS.PRODUCT_ID);
        public static final ForeignKey<OrderDetailsRecord, OrderDetailsStatusRecord> FK_ORDER_DETAILS_ORDER_DETAILS_STATUS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_ORDER_DETAILS_STATUS_PRIMARY, OrderDetails.ORDER_DETAILS, "fk_order_details_order_details_status1", OrderDetails.ORDER_DETAILS.STATUS_ID);
        public static final ForeignKey<PurchaseOrdersRecord, SuppliersRecord> FK_PURCHASE_ORDERS_SUPPLIERS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_SUPPLIERS_PRIMARY, PurchaseOrders.PURCHASE_ORDERS, "fk_purchase_orders_suppliers1", PurchaseOrders.PURCHASE_ORDERS.SUPPLIER_ID);
        public static final ForeignKey<PurchaseOrdersRecord, EmployeesRecord> FK_PURCHASE_ORDERS_EMPLOYEES1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_EMPLOYEES_PRIMARY, PurchaseOrders.PURCHASE_ORDERS, "fk_purchase_orders_employees1", PurchaseOrders.PURCHASE_ORDERS.CREATED_BY);
        public static final ForeignKey<PurchaseOrdersRecord, PurchaseOrderStatusRecord> FK_PURCHASE_ORDERS_PURCHASE_ORDER_STATUS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_PURCHASE_ORDER_STATUS_PRIMARY, PurchaseOrders.PURCHASE_ORDERS, "fk_purchase_orders_purchase_order_status1", PurchaseOrders.PURCHASE_ORDERS.STATUS_ID);
        public static final ForeignKey<PurchaseOrderDetailsRecord, PurchaseOrdersRecord> FK_PURCHASE_ORDER_DETAILS_PURCHASE_ORDERS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_PURCHASE_ORDERS_PRIMARY, PurchaseOrderDetails.PURCHASE_ORDER_DETAILS, "fk_purchase_order_details_purchase_orders1", PurchaseOrderDetails.PURCHASE_ORDER_DETAILS.PURCHASE_ORDER_ID);
        public static final ForeignKey<PurchaseOrderDetailsRecord, ProductsRecord> FK_PURCHASE_ORDER_DETAILS_PRODUCTS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_PRODUCTS_PRIMARY, PurchaseOrderDetails.PURCHASE_ORDER_DETAILS, "fk_purchase_order_details_products1", PurchaseOrderDetails.PURCHASE_ORDER_DETAILS.PRODUCT_ID);
        public static final ForeignKey<PurchaseOrderDetailsRecord, InventoryTransactionsRecord> FK_PURCHASE_ORDER_DETAILS_INVENTORY_TRANSACTIONS1 = Internal.createForeignKey(com.jooq.example.domain.Keys.KEY_INVENTORY_TRANSACTIONS_PRIMARY, PurchaseOrderDetails.PURCHASE_ORDER_DETAILS, "fk_purchase_order_details_inventory_transactions1", PurchaseOrderDetails.PURCHASE_ORDER_DETAILS.INVENTORY_ID);
    }
}
