/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain;


import com.jooq.example.domain.tables.Customers;
import com.jooq.example.domain.tables.EmployeePrivileges;
import com.jooq.example.domain.tables.Employees;
import com.jooq.example.domain.tables.InventoryTransactionTypes;
import com.jooq.example.domain.tables.InventoryTransactions;
import com.jooq.example.domain.tables.Invoices;
import com.jooq.example.domain.tables.OrderDetails;
import com.jooq.example.domain.tables.OrderDetailsStatus;
import com.jooq.example.domain.tables.Orders;
import com.jooq.example.domain.tables.OrdersStatus;
import com.jooq.example.domain.tables.OrdersTaxStatus;
import com.jooq.example.domain.tables.Privileges;
import com.jooq.example.domain.tables.Products;
import com.jooq.example.domain.tables.PurchaseOrderDetails;
import com.jooq.example.domain.tables.PurchaseOrderStatus;
import com.jooq.example.domain.tables.PurchaseOrders;
import com.jooq.example.domain.tables.SalesReports;
import com.jooq.example.domain.tables.Shippers;
import com.jooq.example.domain.tables.Strings;
import com.jooq.example.domain.tables.Suppliers;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in northwind
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>northwind.customers</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>northwind.employees</code>.
     */
    public static final Employees EMPLOYEES = Employees.EMPLOYEES;

    /**
     * The table <code>northwind.employee_privileges</code>.
     */
    public static final EmployeePrivileges EMPLOYEE_PRIVILEGES = EmployeePrivileges.EMPLOYEE_PRIVILEGES;

    /**
     * The table <code>northwind.inventory_transactions</code>.
     */
    public static final InventoryTransactions INVENTORY_TRANSACTIONS = InventoryTransactions.INVENTORY_TRANSACTIONS;

    /**
     * The table <code>northwind.inventory_transaction_types</code>.
     */
    public static final InventoryTransactionTypes INVENTORY_TRANSACTION_TYPES = InventoryTransactionTypes.INVENTORY_TRANSACTION_TYPES;

    /**
     * The table <code>northwind.invoices</code>.
     */
    public static final Invoices INVOICES = Invoices.INVOICES;

    /**
     * The table <code>northwind.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>northwind.orders_status</code>.
     */
    public static final OrdersStatus ORDERS_STATUS = OrdersStatus.ORDERS_STATUS;

    /**
     * The table <code>northwind.orders_tax_status</code>.
     */
    public static final OrdersTaxStatus ORDERS_TAX_STATUS = OrdersTaxStatus.ORDERS_TAX_STATUS;

    /**
     * The table <code>northwind.order_details</code>.
     */
    public static final OrderDetails ORDER_DETAILS = OrderDetails.ORDER_DETAILS;

    /**
     * The table <code>northwind.order_details_status</code>.
     */
    public static final OrderDetailsStatus ORDER_DETAILS_STATUS = OrderDetailsStatus.ORDER_DETAILS_STATUS;

    /**
     * The table <code>northwind.privileges</code>.
     */
    public static final Privileges PRIVILEGES = Privileges.PRIVILEGES;

    /**
     * The table <code>northwind.products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;

    /**
     * The table <code>northwind.purchase_orders</code>.
     */
    public static final PurchaseOrders PURCHASE_ORDERS = PurchaseOrders.PURCHASE_ORDERS;

    /**
     * The table <code>northwind.purchase_order_details</code>.
     */
    public static final PurchaseOrderDetails PURCHASE_ORDER_DETAILS = PurchaseOrderDetails.PURCHASE_ORDER_DETAILS;

    /**
     * The table <code>northwind.purchase_order_status</code>.
     */
    public static final PurchaseOrderStatus PURCHASE_ORDER_STATUS = PurchaseOrderStatus.PURCHASE_ORDER_STATUS;

    /**
     * The table <code>northwind.sales_reports</code>.
     */
    public static final SalesReports SALES_REPORTS = SalesReports.SALES_REPORTS;

    /**
     * The table <code>northwind.shippers</code>.
     */
    public static final Shippers SHIPPERS = Shippers.SHIPPERS;

    /**
     * The table <code>northwind.strings</code>.
     */
    public static final Strings STRINGS = Strings.STRINGS;

    /**
     * The table <code>northwind.suppliers</code>.
     */
    public static final Suppliers SUPPLIERS = Suppliers.SUPPLIERS;
}
