/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.records;


import com.jooq.example.domain.tables.Customers;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomersRecord extends UpdatableRecordImpl<CustomersRecord> implements Record18<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, byte[]> {

    private static final long serialVersionUID = -1959661268;

    /**
     * Setter for <code>northwind.customers.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>northwind.customers.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>northwind.customers.company</code>.
     */
    public void setCompany(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>northwind.customers.company</code>.
     */
    public String getCompany() {
        return (String) get(1);
    }

    /**
     * Setter for <code>northwind.customers.last_name</code>.
     */
    public void setLastName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>northwind.customers.last_name</code>.
     */
    public String getLastName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>northwind.customers.first_name</code>.
     */
    public void setFirstName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>northwind.customers.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>northwind.customers.email_address</code>.
     */
    public void setEmailAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>northwind.customers.email_address</code>.
     */
    public String getEmailAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>northwind.customers.job_title</code>.
     */
    public void setJobTitle(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>northwind.customers.job_title</code>.
     */
    public String getJobTitle() {
        return (String) get(5);
    }

    /**
     * Setter for <code>northwind.customers.business_phone</code>.
     */
    public void setBusinessPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>northwind.customers.business_phone</code>.
     */
    public String getBusinessPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>northwind.customers.home_phone</code>.
     */
    public void setHomePhone(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>northwind.customers.home_phone</code>.
     */
    public String getHomePhone() {
        return (String) get(7);
    }

    /**
     * Setter for <code>northwind.customers.mobile_phone</code>.
     */
    public void setMobilePhone(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>northwind.customers.mobile_phone</code>.
     */
    public String getMobilePhone() {
        return (String) get(8);
    }

    /**
     * Setter for <code>northwind.customers.fax_number</code>.
     */
    public void setFaxNumber(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>northwind.customers.fax_number</code>.
     */
    public String getFaxNumber() {
        return (String) get(9);
    }

    /**
     * Setter for <code>northwind.customers.address</code>.
     */
    public void setAddress(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>northwind.customers.address</code>.
     */
    public String getAddress() {
        return (String) get(10);
    }

    /**
     * Setter for <code>northwind.customers.city</code>.
     */
    public void setCity(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>northwind.customers.city</code>.
     */
    public String getCity() {
        return (String) get(11);
    }

    /**
     * Setter for <code>northwind.customers.state_province</code>.
     */
    public void setStateProvince(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>northwind.customers.state_province</code>.
     */
    public String getStateProvince() {
        return (String) get(12);
    }

    /**
     * Setter for <code>northwind.customers.zip_postal_code</code>.
     */
    public void setZipPostalCode(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>northwind.customers.zip_postal_code</code>.
     */
    public String getZipPostalCode() {
        return (String) get(13);
    }

    /**
     * Setter for <code>northwind.customers.country_region</code>.
     */
    public void setCountryRegion(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>northwind.customers.country_region</code>.
     */
    public String getCountryRegion() {
        return (String) get(14);
    }

    /**
     * Setter for <code>northwind.customers.web_page</code>.
     */
    public void setWebPage(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>northwind.customers.web_page</code>.
     */
    public String getWebPage() {
        return (String) get(15);
    }

    /**
     * Setter for <code>northwind.customers.notes</code>.
     */
    public void setNotes(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>northwind.customers.notes</code>.
     */
    public String getNotes() {
        return (String) get(16);
    }

    /**
     * Setter for <code>northwind.customers.attachments</code>.
     */
    public void setAttachments(byte... value) {
        set(17, value);
    }

    /**
     * Getter for <code>northwind.customers.attachments</code>.
     */
    public byte[] getAttachments() {
        return (byte[]) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, byte[]> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, byte[]> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Customers.CUSTOMERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Customers.CUSTOMERS.COMPANY;
    }

    @Override
    public Field<String> field3() {
        return Customers.CUSTOMERS.LAST_NAME;
    }

    @Override
    public Field<String> field4() {
        return Customers.CUSTOMERS.FIRST_NAME;
    }

    @Override
    public Field<String> field5() {
        return Customers.CUSTOMERS.EMAIL_ADDRESS;
    }

    @Override
    public Field<String> field6() {
        return Customers.CUSTOMERS.JOB_TITLE;
    }

    @Override
    public Field<String> field7() {
        return Customers.CUSTOMERS.BUSINESS_PHONE;
    }

    @Override
    public Field<String> field8() {
        return Customers.CUSTOMERS.HOME_PHONE;
    }

    @Override
    public Field<String> field9() {
        return Customers.CUSTOMERS.MOBILE_PHONE;
    }

    @Override
    public Field<String> field10() {
        return Customers.CUSTOMERS.FAX_NUMBER;
    }

    @Override
    public Field<String> field11() {
        return Customers.CUSTOMERS.ADDRESS;
    }

    @Override
    public Field<String> field12() {
        return Customers.CUSTOMERS.CITY;
    }

    @Override
    public Field<String> field13() {
        return Customers.CUSTOMERS.STATE_PROVINCE;
    }

    @Override
    public Field<String> field14() {
        return Customers.CUSTOMERS.ZIP_POSTAL_CODE;
    }

    @Override
    public Field<String> field15() {
        return Customers.CUSTOMERS.COUNTRY_REGION;
    }

    @Override
    public Field<String> field16() {
        return Customers.CUSTOMERS.WEB_PAGE;
    }

    @Override
    public Field<String> field17() {
        return Customers.CUSTOMERS.NOTES;
    }

    @Override
    public Field<byte[]> field18() {
        return Customers.CUSTOMERS.ATTACHMENTS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCompany();
    }

    @Override
    public String component3() {
        return getLastName();
    }

    @Override
    public String component4() {
        return getFirstName();
    }

    @Override
    public String component5() {
        return getEmailAddress();
    }

    @Override
    public String component6() {
        return getJobTitle();
    }

    @Override
    public String component7() {
        return getBusinessPhone();
    }

    @Override
    public String component8() {
        return getHomePhone();
    }

    @Override
    public String component9() {
        return getMobilePhone();
    }

    @Override
    public String component10() {
        return getFaxNumber();
    }

    @Override
    public String component11() {
        return getAddress();
    }

    @Override
    public String component12() {
        return getCity();
    }

    @Override
    public String component13() {
        return getStateProvince();
    }

    @Override
    public String component14() {
        return getZipPostalCode();
    }

    @Override
    public String component15() {
        return getCountryRegion();
    }

    @Override
    public String component16() {
        return getWebPage();
    }

    @Override
    public String component17() {
        return getNotes();
    }

    @Override
    public byte[] component18() {
        return getAttachments();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCompany();
    }

    @Override
    public String value3() {
        return getLastName();
    }

    @Override
    public String value4() {
        return getFirstName();
    }

    @Override
    public String value5() {
        return getEmailAddress();
    }

    @Override
    public String value6() {
        return getJobTitle();
    }

    @Override
    public String value7() {
        return getBusinessPhone();
    }

    @Override
    public String value8() {
        return getHomePhone();
    }

    @Override
    public String value9() {
        return getMobilePhone();
    }

    @Override
    public String value10() {
        return getFaxNumber();
    }

    @Override
    public String value11() {
        return getAddress();
    }

    @Override
    public String value12() {
        return getCity();
    }

    @Override
    public String value13() {
        return getStateProvince();
    }

    @Override
    public String value14() {
        return getZipPostalCode();
    }

    @Override
    public String value15() {
        return getCountryRegion();
    }

    @Override
    public String value16() {
        return getWebPage();
    }

    @Override
    public String value17() {
        return getNotes();
    }

    @Override
    public byte[] value18() {
        return getAttachments();
    }

    @Override
    public CustomersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CustomersRecord value2(String value) {
        setCompany(value);
        return this;
    }

    @Override
    public CustomersRecord value3(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public CustomersRecord value4(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public CustomersRecord value5(String value) {
        setEmailAddress(value);
        return this;
    }

    @Override
    public CustomersRecord value6(String value) {
        setJobTitle(value);
        return this;
    }

    @Override
    public CustomersRecord value7(String value) {
        setBusinessPhone(value);
        return this;
    }

    @Override
    public CustomersRecord value8(String value) {
        setHomePhone(value);
        return this;
    }

    @Override
    public CustomersRecord value9(String value) {
        setMobilePhone(value);
        return this;
    }

    @Override
    public CustomersRecord value10(String value) {
        setFaxNumber(value);
        return this;
    }

    @Override
    public CustomersRecord value11(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public CustomersRecord value12(String value) {
        setCity(value);
        return this;
    }

    @Override
    public CustomersRecord value13(String value) {
        setStateProvince(value);
        return this;
    }

    @Override
    public CustomersRecord value14(String value) {
        setZipPostalCode(value);
        return this;
    }

    @Override
    public CustomersRecord value15(String value) {
        setCountryRegion(value);
        return this;
    }

    @Override
    public CustomersRecord value16(String value) {
        setWebPage(value);
        return this;
    }

    @Override
    public CustomersRecord value17(String value) {
        setNotes(value);
        return this;
    }

    @Override
    public CustomersRecord value18(byte... value) {
        setAttachments(value);
        return this;
    }

    @Override
    public CustomersRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, String value17, byte[] value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomersRecord
     */
    public CustomersRecord() {
        super(Customers.CUSTOMERS);
    }

    /**
     * Create a detached, initialised CustomersRecord
     */
    public CustomersRecord(Integer id, String company, String lastName, String firstName, String emailAddress, String jobTitle, String businessPhone, String homePhone, String mobilePhone, String faxNumber, String address, String city, String stateProvince, String zipPostalCode, String countryRegion, String webPage, String notes, byte[] attachments) {
        super(Customers.CUSTOMERS);

        set(0, id);
        set(1, company);
        set(2, lastName);
        set(3, firstName);
        set(4, emailAddress);
        set(5, jobTitle);
        set(6, businessPhone);
        set(7, homePhone);
        set(8, mobilePhone);
        set(9, faxNumber);
        set(10, address);
        set(11, city);
        set(12, stateProvince);
        set(13, zipPostalCode);
        set(14, countryRegion);
        set(15, webPage);
        set(16, notes);
        set(17, attachments);
    }
}
