/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.records;


import com.jooq.example.domain.tables.InventoryTransactionTypes;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryTransactionTypesRecord extends UpdatableRecordImpl<InventoryTransactionTypesRecord> implements Record2<Byte, String> {

    private static final long serialVersionUID = 989655401;

    /**
     * Setter for <code>northwind.inventory_transaction_types.id</code>.
     */
    public void setId(Byte value) {
        set(0, value);
    }

    /**
     * Getter for <code>northwind.inventory_transaction_types.id</code>.
     */
    public Byte getId() {
        return (Byte) get(0);
    }

    /**
     * Setter for <code>northwind.inventory_transaction_types.type_name</code>.
     */
    public void setTypeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>northwind.inventory_transaction_types.type_name</code>.
     */
    public String getTypeName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Byte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Byte, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Byte, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Byte> field1() {
        return InventoryTransactionTypes.INVENTORY_TRANSACTION_TYPES.ID;
    }

    @Override
    public Field<String> field2() {
        return InventoryTransactionTypes.INVENTORY_TRANSACTION_TYPES.TYPE_NAME;
    }

    @Override
    public Byte component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTypeName();
    }

    @Override
    public Byte value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTypeName();
    }

    @Override
    public InventoryTransactionTypesRecord value1(Byte value) {
        setId(value);
        return this;
    }

    @Override
    public InventoryTransactionTypesRecord value2(String value) {
        setTypeName(value);
        return this;
    }

    @Override
    public InventoryTransactionTypesRecord values(Byte value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryTransactionTypesRecord
     */
    public InventoryTransactionTypesRecord() {
        super(InventoryTransactionTypes.INVENTORY_TRANSACTION_TYPES);
    }

    /**
     * Create a detached, initialised InventoryTransactionTypesRecord
     */
    public InventoryTransactionTypesRecord(Byte id, String typeName) {
        super(InventoryTransactionTypes.INVENTORY_TRANSACTION_TYPES);

        set(0, id);
        set(1, typeName);
    }
}
