/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.records;


import com.jooq.example.domain.tables.InventoryTransactions;

import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryTransactionsRecord extends UpdatableRecordImpl<InventoryTransactionsRecord> implements Record9<Integer, Byte, Timestamp, Timestamp, Integer, Integer, Integer, Integer, String> {

    private static final long serialVersionUID = -1998026369;

    /**
     * Setter for <code>northwind.inventory_transactions.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>northwind.inventory_transactions.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>northwind.inventory_transactions.transaction_type</code>.
     */
    public void setTransactionType(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>northwind.inventory_transactions.transaction_type</code>.
     */
    public Byte getTransactionType() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>northwind.inventory_transactions.transaction_created_date</code>.
     */
    public void setTransactionCreatedDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>northwind.inventory_transactions.transaction_created_date</code>.
     */
    public Timestamp getTransactionCreatedDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>northwind.inventory_transactions.transaction_modified_date</code>.
     */
    public void setTransactionModifiedDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>northwind.inventory_transactions.transaction_modified_date</code>.
     */
    public Timestamp getTransactionModifiedDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>northwind.inventory_transactions.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>northwind.inventory_transactions.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>northwind.inventory_transactions.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>northwind.inventory_transactions.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>northwind.inventory_transactions.purchase_order_id</code>.
     */
    public void setPurchaseOrderId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>northwind.inventory_transactions.purchase_order_id</code>.
     */
    public Integer getPurchaseOrderId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>northwind.inventory_transactions.customer_order_id</code>.
     */
    public void setCustomerOrderId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>northwind.inventory_transactions.customer_order_id</code>.
     */
    public Integer getCustomerOrderId() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>northwind.inventory_transactions.comments</code>.
     */
    public void setComments(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>northwind.inventory_transactions.comments</code>.
     */
    public String getComments() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, Byte, Timestamp, Timestamp, Integer, Integer, Integer, Integer, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, Byte, Timestamp, Timestamp, Integer, Integer, Integer, Integer, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return InventoryTransactions.INVENTORY_TRANSACTIONS.ID;
    }

    @Override
    public Field<Byte> field2() {
        return InventoryTransactions.INVENTORY_TRANSACTIONS.TRANSACTION_TYPE;
    }

    @Override
    public Field<Timestamp> field3() {
        return InventoryTransactions.INVENTORY_TRANSACTIONS.TRANSACTION_CREATED_DATE;
    }

    @Override
    public Field<Timestamp> field4() {
        return InventoryTransactions.INVENTORY_TRANSACTIONS.TRANSACTION_MODIFIED_DATE;
    }

    @Override
    public Field<Integer> field5() {
        return InventoryTransactions.INVENTORY_TRANSACTIONS.PRODUCT_ID;
    }

    @Override
    public Field<Integer> field6() {
        return InventoryTransactions.INVENTORY_TRANSACTIONS.QUANTITY;
    }

    @Override
    public Field<Integer> field7() {
        return InventoryTransactions.INVENTORY_TRANSACTIONS.PURCHASE_ORDER_ID;
    }

    @Override
    public Field<Integer> field8() {
        return InventoryTransactions.INVENTORY_TRANSACTIONS.CUSTOMER_ORDER_ID;
    }

    @Override
    public Field<String> field9() {
        return InventoryTransactions.INVENTORY_TRANSACTIONS.COMMENTS;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Byte component2() {
        return getTransactionType();
    }

    @Override
    public Timestamp component3() {
        return getTransactionCreatedDate();
    }

    @Override
    public Timestamp component4() {
        return getTransactionModifiedDate();
    }

    @Override
    public Integer component5() {
        return getProductId();
    }

    @Override
    public Integer component6() {
        return getQuantity();
    }

    @Override
    public Integer component7() {
        return getPurchaseOrderId();
    }

    @Override
    public Integer component8() {
        return getCustomerOrderId();
    }

    @Override
    public String component9() {
        return getComments();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Byte value2() {
        return getTransactionType();
    }

    @Override
    public Timestamp value3() {
        return getTransactionCreatedDate();
    }

    @Override
    public Timestamp value4() {
        return getTransactionModifiedDate();
    }

    @Override
    public Integer value5() {
        return getProductId();
    }

    @Override
    public Integer value6() {
        return getQuantity();
    }

    @Override
    public Integer value7() {
        return getPurchaseOrderId();
    }

    @Override
    public Integer value8() {
        return getCustomerOrderId();
    }

    @Override
    public String value9() {
        return getComments();
    }

    @Override
    public InventoryTransactionsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public InventoryTransactionsRecord value2(Byte value) {
        setTransactionType(value);
        return this;
    }

    @Override
    public InventoryTransactionsRecord value3(Timestamp value) {
        setTransactionCreatedDate(value);
        return this;
    }

    @Override
    public InventoryTransactionsRecord value4(Timestamp value) {
        setTransactionModifiedDate(value);
        return this;
    }

    @Override
    public InventoryTransactionsRecord value5(Integer value) {
        setProductId(value);
        return this;
    }

    @Override
    public InventoryTransactionsRecord value6(Integer value) {
        setQuantity(value);
        return this;
    }

    @Override
    public InventoryTransactionsRecord value7(Integer value) {
        setPurchaseOrderId(value);
        return this;
    }

    @Override
    public InventoryTransactionsRecord value8(Integer value) {
        setCustomerOrderId(value);
        return this;
    }

    @Override
    public InventoryTransactionsRecord value9(String value) {
        setComments(value);
        return this;
    }

    @Override
    public InventoryTransactionsRecord values(Integer value1, Byte value2, Timestamp value3, Timestamp value4, Integer value5, Integer value6, Integer value7, Integer value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryTransactionsRecord
     */
    public InventoryTransactionsRecord() {
        super(InventoryTransactions.INVENTORY_TRANSACTIONS);
    }

    /**
     * Create a detached, initialised InventoryTransactionsRecord
     */
    public InventoryTransactionsRecord(Integer id, Byte transactionType, Timestamp transactionCreatedDate, Timestamp transactionModifiedDate, Integer productId, Integer quantity, Integer purchaseOrderId, Integer customerOrderId, String comments) {
        super(InventoryTransactions.INVENTORY_TRANSACTIONS);

        set(0, id);
        set(1, transactionType);
        set(2, transactionCreatedDate);
        set(3, transactionModifiedDate);
        set(4, productId);
        set(5, quantity);
        set(6, purchaseOrderId);
        set(7, customerOrderId);
        set(8, comments);
    }
}
