/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.records;


import com.jooq.example.domain.tables.OrderDetails;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderDetailsRecord extends UpdatableRecordImpl<OrderDetailsRecord> implements Record10<Integer, Integer, Integer, BigDecimal, BigDecimal, Double, Integer, Timestamp, Integer, Integer> {

    private static final long serialVersionUID = 1859742302;

    /**
     * Setter for <code>northwind.order_details.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>northwind.order_details.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>northwind.order_details.order_id</code>.
     */
    public void setOrderId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>northwind.order_details.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>northwind.order_details.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>northwind.order_details.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>northwind.order_details.quantity</code>.
     */
    public void setQuantity(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>northwind.order_details.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>northwind.order_details.unit_price</code>.
     */
    public void setUnitPrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>northwind.order_details.unit_price</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>northwind.order_details.discount</code>.
     */
    public void setDiscount(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>northwind.order_details.discount</code>.
     */
    public Double getDiscount() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>northwind.order_details.status_id</code>.
     */
    public void setStatusId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>northwind.order_details.status_id</code>.
     */
    public Integer getStatusId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>northwind.order_details.date_allocated</code>.
     */
    public void setDateAllocated(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>northwind.order_details.date_allocated</code>.
     */
    public Timestamp getDateAllocated() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>northwind.order_details.purchase_order_id</code>.
     */
    public void setPurchaseOrderId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>northwind.order_details.purchase_order_id</code>.
     */
    public Integer getPurchaseOrderId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>northwind.order_details.inventory_id</code>.
     */
    public void setInventoryId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>northwind.order_details.inventory_id</code>.
     */
    public Integer getInventoryId() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Integer, Integer, Integer, BigDecimal, BigDecimal, Double, Integer, Timestamp, Integer, Integer> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Integer, Integer, Integer, BigDecimal, BigDecimal, Double, Integer, Timestamp, Integer, Integer> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OrderDetails.ORDER_DETAILS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return OrderDetails.ORDER_DETAILS.ORDER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return OrderDetails.ORDER_DETAILS.PRODUCT_ID;
    }

    @Override
    public Field<BigDecimal> field4() {
        return OrderDetails.ORDER_DETAILS.QUANTITY;
    }

    @Override
    public Field<BigDecimal> field5() {
        return OrderDetails.ORDER_DETAILS.UNIT_PRICE;
    }

    @Override
    public Field<Double> field6() {
        return OrderDetails.ORDER_DETAILS.DISCOUNT;
    }

    @Override
    public Field<Integer> field7() {
        return OrderDetails.ORDER_DETAILS.STATUS_ID;
    }

    @Override
    public Field<Timestamp> field8() {
        return OrderDetails.ORDER_DETAILS.DATE_ALLOCATED;
    }

    @Override
    public Field<Integer> field9() {
        return OrderDetails.ORDER_DETAILS.PURCHASE_ORDER_ID;
    }

    @Override
    public Field<Integer> field10() {
        return OrderDetails.ORDER_DETAILS.INVENTORY_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getOrderId();
    }

    @Override
    public Integer component3() {
        return getProductId();
    }

    @Override
    public BigDecimal component4() {
        return getQuantity();
    }

    @Override
    public BigDecimal component5() {
        return getUnitPrice();
    }

    @Override
    public Double component6() {
        return getDiscount();
    }

    @Override
    public Integer component7() {
        return getStatusId();
    }

    @Override
    public Timestamp component8() {
        return getDateAllocated();
    }

    @Override
    public Integer component9() {
        return getPurchaseOrderId();
    }

    @Override
    public Integer component10() {
        return getInventoryId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getOrderId();
    }

    @Override
    public Integer value3() {
        return getProductId();
    }

    @Override
    public BigDecimal value4() {
        return getQuantity();
    }

    @Override
    public BigDecimal value5() {
        return getUnitPrice();
    }

    @Override
    public Double value6() {
        return getDiscount();
    }

    @Override
    public Integer value7() {
        return getStatusId();
    }

    @Override
    public Timestamp value8() {
        return getDateAllocated();
    }

    @Override
    public Integer value9() {
        return getPurchaseOrderId();
    }

    @Override
    public Integer value10() {
        return getInventoryId();
    }

    @Override
    public OrderDetailsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OrderDetailsRecord value2(Integer value) {
        setOrderId(value);
        return this;
    }

    @Override
    public OrderDetailsRecord value3(Integer value) {
        setProductId(value);
        return this;
    }

    @Override
    public OrderDetailsRecord value4(BigDecimal value) {
        setQuantity(value);
        return this;
    }

    @Override
    public OrderDetailsRecord value5(BigDecimal value) {
        setUnitPrice(value);
        return this;
    }

    @Override
    public OrderDetailsRecord value6(Double value) {
        setDiscount(value);
        return this;
    }

    @Override
    public OrderDetailsRecord value7(Integer value) {
        setStatusId(value);
        return this;
    }

    @Override
    public OrderDetailsRecord value8(Timestamp value) {
        setDateAllocated(value);
        return this;
    }

    @Override
    public OrderDetailsRecord value9(Integer value) {
        setPurchaseOrderId(value);
        return this;
    }

    @Override
    public OrderDetailsRecord value10(Integer value) {
        setInventoryId(value);
        return this;
    }

    @Override
    public OrderDetailsRecord values(Integer value1, Integer value2, Integer value3, BigDecimal value4, BigDecimal value5, Double value6, Integer value7, Timestamp value8, Integer value9, Integer value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderDetailsRecord
     */
    public OrderDetailsRecord() {
        super(OrderDetails.ORDER_DETAILS);
    }

    /**
     * Create a detached, initialised OrderDetailsRecord
     */
    public OrderDetailsRecord(Integer id, Integer orderId, Integer productId, BigDecimal quantity, BigDecimal unitPrice, Double discount, Integer statusId, Timestamp dateAllocated, Integer purchaseOrderId, Integer inventoryId) {
        super(OrderDetails.ORDER_DETAILS);

        set(0, id);
        set(1, orderId);
        set(2, productId);
        set(3, quantity);
        set(4, unitPrice);
        set(5, discount);
        set(6, statusId);
        set(7, dateAllocated);
        set(8, purchaseOrderId);
        set(9, inventoryId);
    }
}
