/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.records;


import com.jooq.example.domain.tables.OrderDetailsStatus;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderDetailsStatusRecord extends UpdatableRecordImpl<OrderDetailsStatusRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -105342563;

    /**
     * Setter for <code>northwind.order_details_status.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>northwind.order_details_status.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>northwind.order_details_status.status_name</code>.
     */
    public void setStatusName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>northwind.order_details_status.status_name</code>.
     */
    public String getStatusName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OrderDetailsStatus.ORDER_DETAILS_STATUS.ID;
    }

    @Override
    public Field<String> field2() {
        return OrderDetailsStatus.ORDER_DETAILS_STATUS.STATUS_NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getStatusName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getStatusName();
    }

    @Override
    public OrderDetailsStatusRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OrderDetailsStatusRecord value2(String value) {
        setStatusName(value);
        return this;
    }

    @Override
    public OrderDetailsStatusRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderDetailsStatusRecord
     */
    public OrderDetailsStatusRecord() {
        super(OrderDetailsStatus.ORDER_DETAILS_STATUS);
    }

    /**
     * Create a detached, initialised OrderDetailsStatusRecord
     */
    public OrderDetailsStatusRecord(Integer id, String statusName) {
        super(OrderDetailsStatus.ORDER_DETAILS_STATUS);

        set(0, id);
        set(1, statusName);
    }
}
