/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.records;


import com.jooq.example.domain.tables.Orders;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> implements Record20<Integer, Integer, Integer, Timestamp, Timestamp, Integer, String, String, String, String, String, String, BigDecimal, BigDecimal, String, Timestamp, String, Double, Byte, Byte> {

    private static final long serialVersionUID = -302596087;

    /**
     * Setter for <code>northwind.orders.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>northwind.orders.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>northwind.orders.employee_id</code>.
     */
    public void setEmployeeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>northwind.orders.employee_id</code>.
     */
    public Integer getEmployeeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>northwind.orders.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>northwind.orders.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>northwind.orders.order_date</code>.
     */
    public void setOrderDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>northwind.orders.order_date</code>.
     */
    public Timestamp getOrderDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>northwind.orders.shipped_date</code>.
     */
    public void setShippedDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>northwind.orders.shipped_date</code>.
     */
    public Timestamp getShippedDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>northwind.orders.shipper_id</code>.
     */
    public void setShipperId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>northwind.orders.shipper_id</code>.
     */
    public Integer getShipperId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>northwind.orders.ship_name</code>.
     */
    public void setShipName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>northwind.orders.ship_name</code>.
     */
    public String getShipName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>northwind.orders.ship_address</code>.
     */
    public void setShipAddress(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>northwind.orders.ship_address</code>.
     */
    public String getShipAddress() {
        return (String) get(7);
    }

    /**
     * Setter for <code>northwind.orders.ship_city</code>.
     */
    public void setShipCity(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>northwind.orders.ship_city</code>.
     */
    public String getShipCity() {
        return (String) get(8);
    }

    /**
     * Setter for <code>northwind.orders.ship_state_province</code>.
     */
    public void setShipStateProvince(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>northwind.orders.ship_state_province</code>.
     */
    public String getShipStateProvince() {
        return (String) get(9);
    }

    /**
     * Setter for <code>northwind.orders.ship_zip_postal_code</code>.
     */
    public void setShipZipPostalCode(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>northwind.orders.ship_zip_postal_code</code>.
     */
    public String getShipZipPostalCode() {
        return (String) get(10);
    }

    /**
     * Setter for <code>northwind.orders.ship_country_region</code>.
     */
    public void setShipCountryRegion(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>northwind.orders.ship_country_region</code>.
     */
    public String getShipCountryRegion() {
        return (String) get(11);
    }

    /**
     * Setter for <code>northwind.orders.shipping_fee</code>.
     */
    public void setShippingFee(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>northwind.orders.shipping_fee</code>.
     */
    public BigDecimal getShippingFee() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>northwind.orders.taxes</code>.
     */
    public void setTaxes(BigDecimal value) {
        set(13, value);
    }

    /**
     * Getter for <code>northwind.orders.taxes</code>.
     */
    public BigDecimal getTaxes() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>northwind.orders.payment_type</code>.
     */
    public void setPaymentType(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>northwind.orders.payment_type</code>.
     */
    public String getPaymentType() {
        return (String) get(14);
    }

    /**
     * Setter for <code>northwind.orders.paid_date</code>.
     */
    public void setPaidDate(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>northwind.orders.paid_date</code>.
     */
    public Timestamp getPaidDate() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>northwind.orders.notes</code>.
     */
    public void setNotes(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>northwind.orders.notes</code>.
     */
    public String getNotes() {
        return (String) get(16);
    }

    /**
     * Setter for <code>northwind.orders.tax_rate</code>.
     */
    public void setTaxRate(Double value) {
        set(17, value);
    }

    /**
     * Getter for <code>northwind.orders.tax_rate</code>.
     */
    public Double getTaxRate() {
        return (Double) get(17);
    }

    /**
     * Setter for <code>northwind.orders.tax_status_id</code>.
     */
    public void setTaxStatusId(Byte value) {
        set(18, value);
    }

    /**
     * Getter for <code>northwind.orders.tax_status_id</code>.
     */
    public Byte getTaxStatusId() {
        return (Byte) get(18);
    }

    /**
     * Setter for <code>northwind.orders.status_id</code>.
     */
    public void setStatusId(Byte value) {
        set(19, value);
    }

    /**
     * Getter for <code>northwind.orders.status_id</code>.
     */
    public Byte getStatusId() {
        return (Byte) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row20<Integer, Integer, Integer, Timestamp, Timestamp, Integer, String, String, String, String, String, String, BigDecimal, BigDecimal, String, Timestamp, String, Double, Byte, Byte> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    @Override
    public Row20<Integer, Integer, Integer, Timestamp, Timestamp, Integer, String, String, String, String, String, String, BigDecimal, BigDecimal, String, Timestamp, String, Double, Byte, Byte> valuesRow() {
        return (Row20) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Orders.ORDERS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Orders.ORDERS.EMPLOYEE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Orders.ORDERS.CUSTOMER_ID;
    }

    @Override
    public Field<Timestamp> field4() {
        return Orders.ORDERS.ORDER_DATE;
    }

    @Override
    public Field<Timestamp> field5() {
        return Orders.ORDERS.SHIPPED_DATE;
    }

    @Override
    public Field<Integer> field6() {
        return Orders.ORDERS.SHIPPER_ID;
    }

    @Override
    public Field<String> field7() {
        return Orders.ORDERS.SHIP_NAME;
    }

    @Override
    public Field<String> field8() {
        return Orders.ORDERS.SHIP_ADDRESS;
    }

    @Override
    public Field<String> field9() {
        return Orders.ORDERS.SHIP_CITY;
    }

    @Override
    public Field<String> field10() {
        return Orders.ORDERS.SHIP_STATE_PROVINCE;
    }

    @Override
    public Field<String> field11() {
        return Orders.ORDERS.SHIP_ZIP_POSTAL_CODE;
    }

    @Override
    public Field<String> field12() {
        return Orders.ORDERS.SHIP_COUNTRY_REGION;
    }

    @Override
    public Field<BigDecimal> field13() {
        return Orders.ORDERS.SHIPPING_FEE;
    }

    @Override
    public Field<BigDecimal> field14() {
        return Orders.ORDERS.TAXES;
    }

    @Override
    public Field<String> field15() {
        return Orders.ORDERS.PAYMENT_TYPE;
    }

    @Override
    public Field<Timestamp> field16() {
        return Orders.ORDERS.PAID_DATE;
    }

    @Override
    public Field<String> field17() {
        return Orders.ORDERS.NOTES;
    }

    @Override
    public Field<Double> field18() {
        return Orders.ORDERS.TAX_RATE;
    }

    @Override
    public Field<Byte> field19() {
        return Orders.ORDERS.TAX_STATUS_ID;
    }

    @Override
    public Field<Byte> field20() {
        return Orders.ORDERS.STATUS_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getEmployeeId();
    }

    @Override
    public Integer component3() {
        return getCustomerId();
    }

    @Override
    public Timestamp component4() {
        return getOrderDate();
    }

    @Override
    public Timestamp component5() {
        return getShippedDate();
    }

    @Override
    public Integer component6() {
        return getShipperId();
    }

    @Override
    public String component7() {
        return getShipName();
    }

    @Override
    public String component8() {
        return getShipAddress();
    }

    @Override
    public String component9() {
        return getShipCity();
    }

    @Override
    public String component10() {
        return getShipStateProvince();
    }

    @Override
    public String component11() {
        return getShipZipPostalCode();
    }

    @Override
    public String component12() {
        return getShipCountryRegion();
    }

    @Override
    public BigDecimal component13() {
        return getShippingFee();
    }

    @Override
    public BigDecimal component14() {
        return getTaxes();
    }

    @Override
    public String component15() {
        return getPaymentType();
    }

    @Override
    public Timestamp component16() {
        return getPaidDate();
    }

    @Override
    public String component17() {
        return getNotes();
    }

    @Override
    public Double component18() {
        return getTaxRate();
    }

    @Override
    public Byte component19() {
        return getTaxStatusId();
    }

    @Override
    public Byte component20() {
        return getStatusId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getEmployeeId();
    }

    @Override
    public Integer value3() {
        return getCustomerId();
    }

    @Override
    public Timestamp value4() {
        return getOrderDate();
    }

    @Override
    public Timestamp value5() {
        return getShippedDate();
    }

    @Override
    public Integer value6() {
        return getShipperId();
    }

    @Override
    public String value7() {
        return getShipName();
    }

    @Override
    public String value8() {
        return getShipAddress();
    }

    @Override
    public String value9() {
        return getShipCity();
    }

    @Override
    public String value10() {
        return getShipStateProvince();
    }

    @Override
    public String value11() {
        return getShipZipPostalCode();
    }

    @Override
    public String value12() {
        return getShipCountryRegion();
    }

    @Override
    public BigDecimal value13() {
        return getShippingFee();
    }

    @Override
    public BigDecimal value14() {
        return getTaxes();
    }

    @Override
    public String value15() {
        return getPaymentType();
    }

    @Override
    public Timestamp value16() {
        return getPaidDate();
    }

    @Override
    public String value17() {
        return getNotes();
    }

    @Override
    public Double value18() {
        return getTaxRate();
    }

    @Override
    public Byte value19() {
        return getTaxStatusId();
    }

    @Override
    public Byte value20() {
        return getStatusId();
    }

    @Override
    public OrdersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OrdersRecord value2(Integer value) {
        setEmployeeId(value);
        return this;
    }

    @Override
    public OrdersRecord value3(Integer value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public OrdersRecord value4(Timestamp value) {
        setOrderDate(value);
        return this;
    }

    @Override
    public OrdersRecord value5(Timestamp value) {
        setShippedDate(value);
        return this;
    }

    @Override
    public OrdersRecord value6(Integer value) {
        setShipperId(value);
        return this;
    }

    @Override
    public OrdersRecord value7(String value) {
        setShipName(value);
        return this;
    }

    @Override
    public OrdersRecord value8(String value) {
        setShipAddress(value);
        return this;
    }

    @Override
    public OrdersRecord value9(String value) {
        setShipCity(value);
        return this;
    }

    @Override
    public OrdersRecord value10(String value) {
        setShipStateProvince(value);
        return this;
    }

    @Override
    public OrdersRecord value11(String value) {
        setShipZipPostalCode(value);
        return this;
    }

    @Override
    public OrdersRecord value12(String value) {
        setShipCountryRegion(value);
        return this;
    }

    @Override
    public OrdersRecord value13(BigDecimal value) {
        setShippingFee(value);
        return this;
    }

    @Override
    public OrdersRecord value14(BigDecimal value) {
        setTaxes(value);
        return this;
    }

    @Override
    public OrdersRecord value15(String value) {
        setPaymentType(value);
        return this;
    }

    @Override
    public OrdersRecord value16(Timestamp value) {
        setPaidDate(value);
        return this;
    }

    @Override
    public OrdersRecord value17(String value) {
        setNotes(value);
        return this;
    }

    @Override
    public OrdersRecord value18(Double value) {
        setTaxRate(value);
        return this;
    }

    @Override
    public OrdersRecord value19(Byte value) {
        setTaxStatusId(value);
        return this;
    }

    @Override
    public OrdersRecord value20(Byte value) {
        setStatusId(value);
        return this;
    }

    @Override
    public OrdersRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4, Timestamp value5, Integer value6, String value7, String value8, String value9, String value10, String value11, String value12, BigDecimal value13, BigDecimal value14, String value15, Timestamp value16, String value17, Double value18, Byte value19, Byte value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Integer id, Integer employeeId, Integer customerId, Timestamp orderDate, Timestamp shippedDate, Integer shipperId, String shipName, String shipAddress, String shipCity, String shipStateProvince, String shipZipPostalCode, String shipCountryRegion, BigDecimal shippingFee, BigDecimal taxes, String paymentType, Timestamp paidDate, String notes, Double taxRate, Byte taxStatusId, Byte statusId) {
        super(Orders.ORDERS);

        set(0, id);
        set(1, employeeId);
        set(2, customerId);
        set(3, orderDate);
        set(4, shippedDate);
        set(5, shipperId);
        set(6, shipName);
        set(7, shipAddress);
        set(8, shipCity);
        set(9, shipStateProvince);
        set(10, shipZipPostalCode);
        set(11, shipCountryRegion);
        set(12, shippingFee);
        set(13, taxes);
        set(14, paymentType);
        set(15, paidDate);
        set(16, notes);
        set(17, taxRate);
        set(18, taxStatusId);
        set(19, statusId);
    }
}
