/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.records;


import com.jooq.example.domain.tables.Privileges;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrivilegesRecord extends UpdatableRecordImpl<PrivilegesRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1863600369;

    /**
     * Setter for <code>northwind.privileges.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>northwind.privileges.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>northwind.privileges.privilege_name</code>.
     */
    public void setPrivilegeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>northwind.privileges.privilege_name</code>.
     */
    public String getPrivilegeName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Privileges.PRIVILEGES.ID;
    }

    @Override
    public Field<String> field2() {
        return Privileges.PRIVILEGES.PRIVILEGE_NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPrivilegeName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPrivilegeName();
    }

    @Override
    public PrivilegesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PrivilegesRecord value2(String value) {
        setPrivilegeName(value);
        return this;
    }

    @Override
    public PrivilegesRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrivilegesRecord
     */
    public PrivilegesRecord() {
        super(Privileges.PRIVILEGES);
    }

    /**
     * Create a detached, initialised PrivilegesRecord
     */
    public PrivilegesRecord(Integer id, String privilegeName) {
        super(Privileges.PRIVILEGES);

        set(0, id);
        set(1, privilegeName);
    }
}
