/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.records;


import com.jooq.example.domain.tables.PurchaseOrders;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseOrdersRecord extends UpdatableRecordImpl<PurchaseOrdersRecord> implements Record16<Integer, Integer, Integer, Timestamp, Timestamp, Integer, Timestamp, BigDecimal, BigDecimal, Timestamp, BigDecimal, String, String, Integer, Timestamp, Integer> {

    private static final long serialVersionUID = -1957576243;

    /**
     * Setter for <code>northwind.purchase_orders.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>northwind.purchase_orders.supplier_id</code>.
     */
    public void setSupplierId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.supplier_id</code>.
     */
    public Integer getSupplierId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>northwind.purchase_orders.created_by</code>.
     */
    public void setCreatedBy(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.created_by</code>.
     */
    public Integer getCreatedBy() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>northwind.purchase_orders.submitted_date</code>.
     */
    public void setSubmittedDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.submitted_date</code>.
     */
    public Timestamp getSubmittedDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>northwind.purchase_orders.creation_date</code>.
     */
    public void setCreationDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.creation_date</code>.
     */
    public Timestamp getCreationDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>northwind.purchase_orders.status_id</code>.
     */
    public void setStatusId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.status_id</code>.
     */
    public Integer getStatusId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>northwind.purchase_orders.expected_date</code>.
     */
    public void setExpectedDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.expected_date</code>.
     */
    public Timestamp getExpectedDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>northwind.purchase_orders.shipping_fee</code>.
     */
    public void setShippingFee(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.shipping_fee</code>.
     */
    public BigDecimal getShippingFee() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>northwind.purchase_orders.taxes</code>.
     */
    public void setTaxes(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.taxes</code>.
     */
    public BigDecimal getTaxes() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>northwind.purchase_orders.payment_date</code>.
     */
    public void setPaymentDate(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.payment_date</code>.
     */
    public Timestamp getPaymentDate() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>northwind.purchase_orders.payment_amount</code>.
     */
    public void setPaymentAmount(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.payment_amount</code>.
     */
    public BigDecimal getPaymentAmount() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>northwind.purchase_orders.payment_method</code>.
     */
    public void setPaymentMethod(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.payment_method</code>.
     */
    public String getPaymentMethod() {
        return (String) get(11);
    }

    /**
     * Setter for <code>northwind.purchase_orders.notes</code>.
     */
    public void setNotes(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.notes</code>.
     */
    public String getNotes() {
        return (String) get(12);
    }

    /**
     * Setter for <code>northwind.purchase_orders.approved_by</code>.
     */
    public void setApprovedBy(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.approved_by</code>.
     */
    public Integer getApprovedBy() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>northwind.purchase_orders.approved_date</code>.
     */
    public void setApprovedDate(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.approved_date</code>.
     */
    public Timestamp getApprovedDate() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>northwind.purchase_orders.submitted_by</code>.
     */
    public void setSubmittedBy(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>northwind.purchase_orders.submitted_by</code>.
     */
    public Integer getSubmittedBy() {
        return (Integer) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Integer, Integer, Integer, Timestamp, Timestamp, Integer, Timestamp, BigDecimal, BigDecimal, Timestamp, BigDecimal, String, String, Integer, Timestamp, Integer> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Integer, Integer, Integer, Timestamp, Timestamp, Integer, Timestamp, BigDecimal, BigDecimal, Timestamp, BigDecimal, String, String, Integer, Timestamp, Integer> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return PurchaseOrders.PURCHASE_ORDERS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return PurchaseOrders.PURCHASE_ORDERS.SUPPLIER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return PurchaseOrders.PURCHASE_ORDERS.CREATED_BY;
    }

    @Override
    public Field<Timestamp> field4() {
        return PurchaseOrders.PURCHASE_ORDERS.SUBMITTED_DATE;
    }

    @Override
    public Field<Timestamp> field5() {
        return PurchaseOrders.PURCHASE_ORDERS.CREATION_DATE;
    }

    @Override
    public Field<Integer> field6() {
        return PurchaseOrders.PURCHASE_ORDERS.STATUS_ID;
    }

    @Override
    public Field<Timestamp> field7() {
        return PurchaseOrders.PURCHASE_ORDERS.EXPECTED_DATE;
    }

    @Override
    public Field<BigDecimal> field8() {
        return PurchaseOrders.PURCHASE_ORDERS.SHIPPING_FEE;
    }

    @Override
    public Field<BigDecimal> field9() {
        return PurchaseOrders.PURCHASE_ORDERS.TAXES;
    }

    @Override
    public Field<Timestamp> field10() {
        return PurchaseOrders.PURCHASE_ORDERS.PAYMENT_DATE;
    }

    @Override
    public Field<BigDecimal> field11() {
        return PurchaseOrders.PURCHASE_ORDERS.PAYMENT_AMOUNT;
    }

    @Override
    public Field<String> field12() {
        return PurchaseOrders.PURCHASE_ORDERS.PAYMENT_METHOD;
    }

    @Override
    public Field<String> field13() {
        return PurchaseOrders.PURCHASE_ORDERS.NOTES;
    }

    @Override
    public Field<Integer> field14() {
        return PurchaseOrders.PURCHASE_ORDERS.APPROVED_BY;
    }

    @Override
    public Field<Timestamp> field15() {
        return PurchaseOrders.PURCHASE_ORDERS.APPROVED_DATE;
    }

    @Override
    public Field<Integer> field16() {
        return PurchaseOrders.PURCHASE_ORDERS.SUBMITTED_BY;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getSupplierId();
    }

    @Override
    public Integer component3() {
        return getCreatedBy();
    }

    @Override
    public Timestamp component4() {
        return getSubmittedDate();
    }

    @Override
    public Timestamp component5() {
        return getCreationDate();
    }

    @Override
    public Integer component6() {
        return getStatusId();
    }

    @Override
    public Timestamp component7() {
        return getExpectedDate();
    }

    @Override
    public BigDecimal component8() {
        return getShippingFee();
    }

    @Override
    public BigDecimal component9() {
        return getTaxes();
    }

    @Override
    public Timestamp component10() {
        return getPaymentDate();
    }

    @Override
    public BigDecimal component11() {
        return getPaymentAmount();
    }

    @Override
    public String component12() {
        return getPaymentMethod();
    }

    @Override
    public String component13() {
        return getNotes();
    }

    @Override
    public Integer component14() {
        return getApprovedBy();
    }

    @Override
    public Timestamp component15() {
        return getApprovedDate();
    }

    @Override
    public Integer component16() {
        return getSubmittedBy();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getSupplierId();
    }

    @Override
    public Integer value3() {
        return getCreatedBy();
    }

    @Override
    public Timestamp value4() {
        return getSubmittedDate();
    }

    @Override
    public Timestamp value5() {
        return getCreationDate();
    }

    @Override
    public Integer value6() {
        return getStatusId();
    }

    @Override
    public Timestamp value7() {
        return getExpectedDate();
    }

    @Override
    public BigDecimal value8() {
        return getShippingFee();
    }

    @Override
    public BigDecimal value9() {
        return getTaxes();
    }

    @Override
    public Timestamp value10() {
        return getPaymentDate();
    }

    @Override
    public BigDecimal value11() {
        return getPaymentAmount();
    }

    @Override
    public String value12() {
        return getPaymentMethod();
    }

    @Override
    public String value13() {
        return getNotes();
    }

    @Override
    public Integer value14() {
        return getApprovedBy();
    }

    @Override
    public Timestamp value15() {
        return getApprovedDate();
    }

    @Override
    public Integer value16() {
        return getSubmittedBy();
    }

    @Override
    public PurchaseOrdersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value2(Integer value) {
        setSupplierId(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value3(Integer value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value4(Timestamp value) {
        setSubmittedDate(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value5(Timestamp value) {
        setCreationDate(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value6(Integer value) {
        setStatusId(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value7(Timestamp value) {
        setExpectedDate(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value8(BigDecimal value) {
        setShippingFee(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value9(BigDecimal value) {
        setTaxes(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value10(Timestamp value) {
        setPaymentDate(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value11(BigDecimal value) {
        setPaymentAmount(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value12(String value) {
        setPaymentMethod(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value13(String value) {
        setNotes(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value14(Integer value) {
        setApprovedBy(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value15(Timestamp value) {
        setApprovedDate(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord value16(Integer value) {
        setSubmittedBy(value);
        return this;
    }

    @Override
    public PurchaseOrdersRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4, Timestamp value5, Integer value6, Timestamp value7, BigDecimal value8, BigDecimal value9, Timestamp value10, BigDecimal value11, String value12, String value13, Integer value14, Timestamp value15, Integer value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchaseOrdersRecord
     */
    public PurchaseOrdersRecord() {
        super(PurchaseOrders.PURCHASE_ORDERS);
    }

    /**
     * Create a detached, initialised PurchaseOrdersRecord
     */
    public PurchaseOrdersRecord(Integer id, Integer supplierId, Integer createdBy, Timestamp submittedDate, Timestamp creationDate, Integer statusId, Timestamp expectedDate, BigDecimal shippingFee, BigDecimal taxes, Timestamp paymentDate, BigDecimal paymentAmount, String paymentMethod, String notes, Integer approvedBy, Timestamp approvedDate, Integer submittedBy) {
        super(PurchaseOrders.PURCHASE_ORDERS);

        set(0, id);
        set(1, supplierId);
        set(2, createdBy);
        set(3, submittedDate);
        set(4, creationDate);
        set(5, statusId);
        set(6, expectedDate);
        set(7, shippingFee);
        set(8, taxes);
        set(9, paymentDate);
        set(10, paymentAmount);
        set(11, paymentMethod);
        set(12, notes);
        set(13, approvedBy);
        set(14, approvedDate);
        set(15, submittedBy);
    }
}
