/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.records;


import com.jooq.example.domain.tables.Strings;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StringsRecord extends UpdatableRecordImpl<StringsRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -542317950;

    /**
     * Setter for <code>northwind.strings.string_id</code>.
     */
    public void setStringId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>northwind.strings.string_id</code>.
     */
    public Integer getStringId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>northwind.strings.string_data</code>.
     */
    public void setStringData(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>northwind.strings.string_data</code>.
     */
    public String getStringData() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Strings.STRINGS.STRING_ID;
    }

    @Override
    public Field<String> field2() {
        return Strings.STRINGS.STRING_DATA;
    }

    @Override
    public Integer component1() {
        return getStringId();
    }

    @Override
    public String component2() {
        return getStringData();
    }

    @Override
    public Integer value1() {
        return getStringId();
    }

    @Override
    public String value2() {
        return getStringData();
    }

    @Override
    public StringsRecord value1(Integer value) {
        setStringId(value);
        return this;
    }

    @Override
    public StringsRecord value2(String value) {
        setStringData(value);
        return this;
    }

    @Override
    public StringsRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StringsRecord
     */
    public StringsRecord() {
        super(Strings.STRINGS);
    }

    /**
     * Create a detached, initialised StringsRecord
     */
    public StringsRecord(Integer stringId, String stringData) {
        super(Strings.STRINGS);

        set(0, stringId);
        set(1, stringData);
    }
}
