/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Customers implements Serializable {

    private static final long serialVersionUID = 101130144;

    private Integer id;
    private String  company;
    private String  lastName;
    private String  firstName;
    private String  emailAddress;
    private String  jobTitle;
    private String  businessPhone;
    private String  homePhone;
    private String  mobilePhone;
    private String  faxNumber;
    private String  address;
    private String  city;
    private String  stateProvince;
    private String  zipPostalCode;
    private String  countryRegion;
    private String  webPage;
    private String  notes;
    private byte[]  attachments;

    public Customers() {}

    public Customers(Customers value) {
        this.id = value.id;
        this.company = value.company;
        this.lastName = value.lastName;
        this.firstName = value.firstName;
        this.emailAddress = value.emailAddress;
        this.jobTitle = value.jobTitle;
        this.businessPhone = value.businessPhone;
        this.homePhone = value.homePhone;
        this.mobilePhone = value.mobilePhone;
        this.faxNumber = value.faxNumber;
        this.address = value.address;
        this.city = value.city;
        this.stateProvince = value.stateProvince;
        this.zipPostalCode = value.zipPostalCode;
        this.countryRegion = value.countryRegion;
        this.webPage = value.webPage;
        this.notes = value.notes;
        this.attachments = value.attachments;
    }

    public Customers(
        Integer id,
        String  company,
        String  lastName,
        String  firstName,
        String  emailAddress,
        String  jobTitle,
        String  businessPhone,
        String  homePhone,
        String  mobilePhone,
        String  faxNumber,
        String  address,
        String  city,
        String  stateProvince,
        String  zipPostalCode,
        String  countryRegion,
        String  webPage,
        String  notes,
        byte[]  attachments
    ) {
        this.id = id;
        this.company = company;
        this.lastName = lastName;
        this.firstName = firstName;
        this.emailAddress = emailAddress;
        this.jobTitle = jobTitle;
        this.businessPhone = businessPhone;
        this.homePhone = homePhone;
        this.mobilePhone = mobilePhone;
        this.faxNumber = faxNumber;
        this.address = address;
        this.city = city;
        this.stateProvince = stateProvince;
        this.zipPostalCode = zipPostalCode;
        this.countryRegion = countryRegion;
        this.webPage = webPage;
        this.notes = notes;
        this.attachments = attachments;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCompany() {
        return this.company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public String getJobTitle() {
        return this.jobTitle;
    }

    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    public String getBusinessPhone() {
        return this.businessPhone;
    }

    public void setBusinessPhone(String businessPhone) {
        this.businessPhone = businessPhone;
    }

    public String getHomePhone() {
        return this.homePhone;
    }

    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }

    public String getMobilePhone() {
        return this.mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    public String getFaxNumber() {
        return this.faxNumber;
    }

    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStateProvince() {
        return this.stateProvince;
    }

    public void setStateProvince(String stateProvince) {
        this.stateProvince = stateProvince;
    }

    public String getZipPostalCode() {
        return this.zipPostalCode;
    }

    public void setZipPostalCode(String zipPostalCode) {
        this.zipPostalCode = zipPostalCode;
    }

    public String getCountryRegion() {
        return this.countryRegion;
    }

    public void setCountryRegion(String countryRegion) {
        this.countryRegion = countryRegion;
    }

    public String getWebPage() {
        return this.webPage;
    }

    public void setWebPage(String webPage) {
        this.webPage = webPage;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public byte[] getAttachments() {
        return this.attachments;
    }

    public void setAttachments(byte... attachments) {
        this.attachments = attachments;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Customers (");

        sb.append(id);
        sb.append(", ").append(company);
        sb.append(", ").append(lastName);
        sb.append(", ").append(firstName);
        sb.append(", ").append(emailAddress);
        sb.append(", ").append(jobTitle);
        sb.append(", ").append(businessPhone);
        sb.append(", ").append(homePhone);
        sb.append(", ").append(mobilePhone);
        sb.append(", ").append(faxNumber);
        sb.append(", ").append(address);
        sb.append(", ").append(city);
        sb.append(", ").append(stateProvince);
        sb.append(", ").append(zipPostalCode);
        sb.append(", ").append(countryRegion);
        sb.append(", ").append(webPage);
        sb.append(", ").append(notes);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
