/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryTransactionTypes implements Serializable {

    private static final long serialVersionUID = -791493078;

    private Byte   id;
    private String typeName;

    public InventoryTransactionTypes() {}

    public InventoryTransactionTypes(InventoryTransactionTypes value) {
        this.id = value.id;
        this.typeName = value.typeName;
    }

    public InventoryTransactionTypes(
        Byte   id,
        String typeName
    ) {
        this.id = id;
        this.typeName = typeName;
    }

    public Byte getId() {
        return this.id;
    }

    public void setId(Byte id) {
        this.id = id;
    }

    public String getTypeName() {
        return this.typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("InventoryTransactionTypes (");

        sb.append(id);
        sb.append(", ").append(typeName);

        sb.append(")");
        return sb.toString();
    }
}
