/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderDetails implements Serializable {

    private static final long serialVersionUID = 824270333;

    private Integer    id;
    private Integer    orderId;
    private Integer    productId;
    private BigDecimal quantity;
    private BigDecimal unitPrice;
    private Double     discount;
    private Integer    statusId;
    private Timestamp  dateAllocated;
    private Integer    purchaseOrderId;
    private Integer    inventoryId;

    public OrderDetails() {}

    public OrderDetails(OrderDetails value) {
        this.id = value.id;
        this.orderId = value.orderId;
        this.productId = value.productId;
        this.quantity = value.quantity;
        this.unitPrice = value.unitPrice;
        this.discount = value.discount;
        this.statusId = value.statusId;
        this.dateAllocated = value.dateAllocated;
        this.purchaseOrderId = value.purchaseOrderId;
        this.inventoryId = value.inventoryId;
    }

    public OrderDetails(
        Integer    id,
        Integer    orderId,
        Integer    productId,
        BigDecimal quantity,
        BigDecimal unitPrice,
        Double     discount,
        Integer    statusId,
        Timestamp  dateAllocated,
        Integer    purchaseOrderId,
        Integer    inventoryId
    ) {
        this.id = id;
        this.orderId = orderId;
        this.productId = productId;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
        this.discount = discount;
        this.statusId = statusId;
        this.dateAllocated = dateAllocated;
        this.purchaseOrderId = purchaseOrderId;
        this.inventoryId = inventoryId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Integer getProductId() {
        return this.productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public BigDecimal getQuantity() {
        return this.quantity;
    }

    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Double getDiscount() {
        return this.discount;
    }

    public void setDiscount(Double discount) {
        this.discount = discount;
    }

    public Integer getStatusId() {
        return this.statusId;
    }

    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    public Timestamp getDateAllocated() {
        return this.dateAllocated;
    }

    public void setDateAllocated(Timestamp dateAllocated) {
        this.dateAllocated = dateAllocated;
    }

    public Integer getPurchaseOrderId() {
        return this.purchaseOrderId;
    }

    public void setPurchaseOrderId(Integer purchaseOrderId) {
        this.purchaseOrderId = purchaseOrderId;
    }

    public Integer getInventoryId() {
        return this.inventoryId;
    }

    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderDetails (");

        sb.append(id);
        sb.append(", ").append(orderId);
        sb.append(", ").append(productId);
        sb.append(", ").append(quantity);
        sb.append(", ").append(unitPrice);
        sb.append(", ").append(discount);
        sb.append(", ").append(statusId);
        sb.append(", ").append(dateAllocated);
        sb.append(", ").append(purchaseOrderId);
        sb.append(", ").append(inventoryId);

        sb.append(")");
        return sb.toString();
    }
}
