/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrdersTaxStatus implements Serializable {

    private static final long serialVersionUID = -1095152333;

    private Byte   id;
    private String taxStatusName;

    public OrdersTaxStatus() {}

    public OrdersTaxStatus(OrdersTaxStatus value) {
        this.id = value.id;
        this.taxStatusName = value.taxStatusName;
    }

    public OrdersTaxStatus(
        Byte   id,
        String taxStatusName
    ) {
        this.id = id;
        this.taxStatusName = taxStatusName;
    }

    public Byte getId() {
        return this.id;
    }

    public void setId(Byte id) {
        this.id = id;
    }

    public String getTaxStatusName() {
        return this.taxStatusName;
    }

    public void setTaxStatusName(String taxStatusName) {
        this.taxStatusName = taxStatusName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrdersTaxStatus (");

        sb.append(id);
        sb.append(", ").append(taxStatusName);

        sb.append(")");
        return sb.toString();
    }
}
