/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderDetailsStatus implements Serializable {

    private static final long serialVersionUID = -577531056;

    private Integer id;
    private String  statusName;

    public OrderDetailsStatus() {}

    public OrderDetailsStatus(OrderDetailsStatus value) {
        this.id = value.id;
        this.statusName = value.statusName;
    }

    public OrderDetailsStatus(
        Integer id,
        String  statusName
    ) {
        this.id = id;
        this.statusName = statusName;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getStatusName() {
        return this.statusName;
    }

    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderDetailsStatus (");

        sb.append(id);
        sb.append(", ").append(statusName);

        sb.append(")");
        return sb.toString();
    }
}
