/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Privileges implements Serializable {

    private static final long serialVersionUID = 1068716261;

    private Integer id;
    private String  privilegeName;

    public Privileges() {}

    public Privileges(Privileges value) {
        this.id = value.id;
        this.privilegeName = value.privilegeName;
    }

    public Privileges(
        Integer id,
        String  privilegeName
    ) {
        this.id = id;
        this.privilegeName = privilegeName;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPrivilegeName() {
        return this.privilegeName;
    }

    public void setPrivilegeName(String privilegeName) {
        this.privilegeName = privilegeName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Privileges (");

        sb.append(id);
        sb.append(", ").append(privilegeName);

        sb.append(")");
        return sb.toString();
    }
}
