/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Products implements Serializable {

    private static final long serialVersionUID = -173134853;

    private String     supplierIds;
    private Integer    id;
    private String     productCode;
    private String     productName;
    private String     description;
    private BigDecimal standardCost;
    private BigDecimal listPrice;
    private Integer    reorderLevel;
    private Integer    targetLevel;
    private String     quantityPerUnit;
    private Byte       discontinued;
    private Integer    minimumReorderQuantity;
    private String     category;
    private byte[]     attachments;

    public Products() {}

    public Products(Products value) {
        this.supplierIds = value.supplierIds;
        this.id = value.id;
        this.productCode = value.productCode;
        this.productName = value.productName;
        this.description = value.description;
        this.standardCost = value.standardCost;
        this.listPrice = value.listPrice;
        this.reorderLevel = value.reorderLevel;
        this.targetLevel = value.targetLevel;
        this.quantityPerUnit = value.quantityPerUnit;
        this.discontinued = value.discontinued;
        this.minimumReorderQuantity = value.minimumReorderQuantity;
        this.category = value.category;
        this.attachments = value.attachments;
    }

    public Products(
        String     supplierIds,
        Integer    id,
        String     productCode,
        String     productName,
        String     description,
        BigDecimal standardCost,
        BigDecimal listPrice,
        Integer    reorderLevel,
        Integer    targetLevel,
        String     quantityPerUnit,
        Byte       discontinued,
        Integer    minimumReorderQuantity,
        String     category,
        byte[]     attachments
    ) {
        this.supplierIds = supplierIds;
        this.id = id;
        this.productCode = productCode;
        this.productName = productName;
        this.description = description;
        this.standardCost = standardCost;
        this.listPrice = listPrice;
        this.reorderLevel = reorderLevel;
        this.targetLevel = targetLevel;
        this.quantityPerUnit = quantityPerUnit;
        this.discontinued = discontinued;
        this.minimumReorderQuantity = minimumReorderQuantity;
        this.category = category;
        this.attachments = attachments;
    }

    public String getSupplierIds() {
        return this.supplierIds;
    }

    public void setSupplierIds(String supplierIds) {
        this.supplierIds = supplierIds;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getProductCode() {
        return this.productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public String getProductName() {
        return this.productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getStandardCost() {
        return this.standardCost;
    }

    public void setStandardCost(BigDecimal standardCost) {
        this.standardCost = standardCost;
    }

    public BigDecimal getListPrice() {
        return this.listPrice;
    }

    public void setListPrice(BigDecimal listPrice) {
        this.listPrice = listPrice;
    }

    public Integer getReorderLevel() {
        return this.reorderLevel;
    }

    public void setReorderLevel(Integer reorderLevel) {
        this.reorderLevel = reorderLevel;
    }

    public Integer getTargetLevel() {
        return this.targetLevel;
    }

    public void setTargetLevel(Integer targetLevel) {
        this.targetLevel = targetLevel;
    }

    public String getQuantityPerUnit() {
        return this.quantityPerUnit;
    }

    public void setQuantityPerUnit(String quantityPerUnit) {
        this.quantityPerUnit = quantityPerUnit;
    }

    public Byte getDiscontinued() {
        return this.discontinued;
    }

    public void setDiscontinued(Byte discontinued) {
        this.discontinued = discontinued;
    }

    public Integer getMinimumReorderQuantity() {
        return this.minimumReorderQuantity;
    }

    public void setMinimumReorderQuantity(Integer minimumReorderQuantity) {
        this.minimumReorderQuantity = minimumReorderQuantity;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public byte[] getAttachments() {
        return this.attachments;
    }

    public void setAttachments(byte... attachments) {
        this.attachments = attachments;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Products (");

        sb.append(supplierIds);
        sb.append(", ").append(id);
        sb.append(", ").append(productCode);
        sb.append(", ").append(productName);
        sb.append(", ").append(description);
        sb.append(", ").append(standardCost);
        sb.append(", ").append(listPrice);
        sb.append(", ").append(reorderLevel);
        sb.append(", ").append(targetLevel);
        sb.append(", ").append(quantityPerUnit);
        sb.append(", ").append(discontinued);
        sb.append(", ").append(minimumReorderQuantity);
        sb.append(", ").append(category);
        sb.append(", ").append("[binary...]");

        sb.append(")");
        return sb.toString();
    }
}
