/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseOrders implements Serializable {

    private static final long serialVersionUID = -16178641;

    private Integer    id;
    private Integer    supplierId;
    private Integer    createdBy;
    private Timestamp  submittedDate;
    private Timestamp  creationDate;
    private Integer    statusId;
    private Timestamp  expectedDate;
    private BigDecimal shippingFee;
    private BigDecimal taxes;
    private Timestamp  paymentDate;
    private BigDecimal paymentAmount;
    private String     paymentMethod;
    private String     notes;
    private Integer    approvedBy;
    private Timestamp  approvedDate;
    private Integer    submittedBy;

    public PurchaseOrders() {}

    public PurchaseOrders(PurchaseOrders value) {
        this.id = value.id;
        this.supplierId = value.supplierId;
        this.createdBy = value.createdBy;
        this.submittedDate = value.submittedDate;
        this.creationDate = value.creationDate;
        this.statusId = value.statusId;
        this.expectedDate = value.expectedDate;
        this.shippingFee = value.shippingFee;
        this.taxes = value.taxes;
        this.paymentDate = value.paymentDate;
        this.paymentAmount = value.paymentAmount;
        this.paymentMethod = value.paymentMethod;
        this.notes = value.notes;
        this.approvedBy = value.approvedBy;
        this.approvedDate = value.approvedDate;
        this.submittedBy = value.submittedBy;
    }

    public PurchaseOrders(
        Integer    id,
        Integer    supplierId,
        Integer    createdBy,
        Timestamp  submittedDate,
        Timestamp  creationDate,
        Integer    statusId,
        Timestamp  expectedDate,
        BigDecimal shippingFee,
        BigDecimal taxes,
        Timestamp  paymentDate,
        BigDecimal paymentAmount,
        String     paymentMethod,
        String     notes,
        Integer    approvedBy,
        Timestamp  approvedDate,
        Integer    submittedBy
    ) {
        this.id = id;
        this.supplierId = supplierId;
        this.createdBy = createdBy;
        this.submittedDate = submittedDate;
        this.creationDate = creationDate;
        this.statusId = statusId;
        this.expectedDate = expectedDate;
        this.shippingFee = shippingFee;
        this.taxes = taxes;
        this.paymentDate = paymentDate;
        this.paymentAmount = paymentAmount;
        this.paymentMethod = paymentMethod;
        this.notes = notes;
        this.approvedBy = approvedBy;
        this.approvedDate = approvedDate;
        this.submittedBy = submittedBy;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getSupplierId() {
        return this.supplierId;
    }

    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getSubmittedDate() {
        return this.submittedDate;
    }

    public void setSubmittedDate(Timestamp submittedDate) {
        this.submittedDate = submittedDate;
    }

    public Timestamp getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Timestamp creationDate) {
        this.creationDate = creationDate;
    }

    public Integer getStatusId() {
        return this.statusId;
    }

    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    public Timestamp getExpectedDate() {
        return this.expectedDate;
    }

    public void setExpectedDate(Timestamp expectedDate) {
        this.expectedDate = expectedDate;
    }

    public BigDecimal getShippingFee() {
        return this.shippingFee;
    }

    public void setShippingFee(BigDecimal shippingFee) {
        this.shippingFee = shippingFee;
    }

    public BigDecimal getTaxes() {
        return this.taxes;
    }

    public void setTaxes(BigDecimal taxes) {
        this.taxes = taxes;
    }

    public Timestamp getPaymentDate() {
        return this.paymentDate;
    }

    public void setPaymentDate(Timestamp paymentDate) {
        this.paymentDate = paymentDate;
    }

    public BigDecimal getPaymentAmount() {
        return this.paymentAmount;
    }

    public void setPaymentAmount(BigDecimal paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    public String getPaymentMethod() {
        return this.paymentMethod;
    }

    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Integer getApprovedBy() {
        return this.approvedBy;
    }

    public void setApprovedBy(Integer approvedBy) {
        this.approvedBy = approvedBy;
    }

    public Timestamp getApprovedDate() {
        return this.approvedDate;
    }

    public void setApprovedDate(Timestamp approvedDate) {
        this.approvedDate = approvedDate;
    }

    public Integer getSubmittedBy() {
        return this.submittedBy;
    }

    public void setSubmittedBy(Integer submittedBy) {
        this.submittedBy = submittedBy;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PurchaseOrders (");

        sb.append(id);
        sb.append(", ").append(supplierId);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(submittedDate);
        sb.append(", ").append(creationDate);
        sb.append(", ").append(statusId);
        sb.append(", ").append(expectedDate);
        sb.append(", ").append(shippingFee);
        sb.append(", ").append(taxes);
        sb.append(", ").append(paymentDate);
        sb.append(", ").append(paymentAmount);
        sb.append(", ").append(paymentMethod);
        sb.append(", ").append(notes);
        sb.append(", ").append(approvedBy);
        sb.append(", ").append(approvedDate);
        sb.append(", ").append(submittedBy);

        sb.append(")");
        return sb.toString();
    }
}
