/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseOrderDetails implements Serializable {

    private static final long serialVersionUID = 1536769230;

    private Integer    id;
    private Integer    purchaseOrderId;
    private Integer    productId;
    private BigDecimal quantity;
    private BigDecimal unitCost;
    private Timestamp  dateReceived;
    private Byte       postedToInventory;
    private Integer    inventoryId;

    public PurchaseOrderDetails() {}

    public PurchaseOrderDetails(PurchaseOrderDetails value) {
        this.id = value.id;
        this.purchaseOrderId = value.purchaseOrderId;
        this.productId = value.productId;
        this.quantity = value.quantity;
        this.unitCost = value.unitCost;
        this.dateReceived = value.dateReceived;
        this.postedToInventory = value.postedToInventory;
        this.inventoryId = value.inventoryId;
    }

    public PurchaseOrderDetails(
        Integer    id,
        Integer    purchaseOrderId,
        Integer    productId,
        BigDecimal quantity,
        BigDecimal unitCost,
        Timestamp  dateReceived,
        Byte       postedToInventory,
        Integer    inventoryId
    ) {
        this.id = id;
        this.purchaseOrderId = purchaseOrderId;
        this.productId = productId;
        this.quantity = quantity;
        this.unitCost = unitCost;
        this.dateReceived = dateReceived;
        this.postedToInventory = postedToInventory;
        this.inventoryId = inventoryId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPurchaseOrderId() {
        return this.purchaseOrderId;
    }

    public void setPurchaseOrderId(Integer purchaseOrderId) {
        this.purchaseOrderId = purchaseOrderId;
    }

    public Integer getProductId() {
        return this.productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    public BigDecimal getQuantity() {
        return this.quantity;
    }

    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getUnitCost() {
        return this.unitCost;
    }

    public void setUnitCost(BigDecimal unitCost) {
        this.unitCost = unitCost;
    }

    public Timestamp getDateReceived() {
        return this.dateReceived;
    }

    public void setDateReceived(Timestamp dateReceived) {
        this.dateReceived = dateReceived;
    }

    public Byte getPostedToInventory() {
        return this.postedToInventory;
    }

    public void setPostedToInventory(Byte postedToInventory) {
        this.postedToInventory = postedToInventory;
    }

    public Integer getInventoryId() {
        return this.inventoryId;
    }

    public void setInventoryId(Integer inventoryId) {
        this.inventoryId = inventoryId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PurchaseOrderDetails (");

        sb.append(id);
        sb.append(", ").append(purchaseOrderId);
        sb.append(", ").append(productId);
        sb.append(", ").append(quantity);
        sb.append(", ").append(unitCost);
        sb.append(", ").append(dateReceived);
        sb.append(", ").append(postedToInventory);
        sb.append(", ").append(inventoryId);

        sb.append(")");
        return sb.toString();
    }
}
