/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseOrderStatus implements Serializable {

    private static final long serialVersionUID = 1455110865;

    private Integer id;
    private String  status;

    public PurchaseOrderStatus() {}

    public PurchaseOrderStatus(PurchaseOrderStatus value) {
        this.id = value.id;
        this.status = value.status;
    }

    public PurchaseOrderStatus(
        Integer id,
        String  status
    ) {
        this.id = id;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PurchaseOrderStatus (");

        sb.append(id);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
