/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesReports implements Serializable {

    private static final long serialVersionUID = 250716713;

    private String groupBy;
    private String display;
    private String title;
    private String filterRowSource;
    private Byte   default_;

    public SalesReports() {}

    public SalesReports(SalesReports value) {
        this.groupBy = value.groupBy;
        this.display = value.display;
        this.title = value.title;
        this.filterRowSource = value.filterRowSource;
        this.default_ = value.default_;
    }

    public SalesReports(
        String groupBy,
        String display,
        String title,
        String filterRowSource,
        Byte   default_
    ) {
        this.groupBy = groupBy;
        this.display = display;
        this.title = title;
        this.filterRowSource = filterRowSource;
        this.default_ = default_;
    }

    public String getGroupBy() {
        return this.groupBy;
    }

    public void setGroupBy(String groupBy) {
        this.groupBy = groupBy;
    }

    public String getDisplay() {
        return this.display;
    }

    public void setDisplay(String display) {
        this.display = display;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getFilterRowSource() {
        return this.filterRowSource;
    }

    public void setFilterRowSource(String filterRowSource) {
        this.filterRowSource = filterRowSource;
    }

    public Byte getDefault() {
        return this.default_;
    }

    public void setDefault(Byte default_) {
        this.default_ = default_;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SalesReports (");

        sb.append(groupBy);
        sb.append(", ").append(display);
        sb.append(", ").append(title);
        sb.append(", ").append(filterRowSource);
        sb.append(", ").append(default_);

        sb.append(")");
        return sb.toString();
    }
}
