/*
 * This file is generated by jOOQ.
 */
package com.jooq.example.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Strings implements Serializable {

    private static final long serialVersionUID = -1484282307;

    private Integer stringId;
    private String  stringData;

    public Strings() {}

    public Strings(Strings value) {
        this.stringId = value.stringId;
        this.stringData = value.stringData;
    }

    public Strings(
        Integer stringId,
        String  stringData
    ) {
        this.stringId = stringId;
        this.stringData = stringData;
    }

    public Integer getStringId() {
        return this.stringId;
    }

    public void setStringId(Integer stringId) {
        this.stringId = stringId;
    }

    public String getStringData() {
        return this.stringData;
    }

    public void setStringData(String stringData) {
        this.stringData = stringData;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Strings (");

        sb.append(stringId);
        sb.append(", ").append(stringData);

        sb.append(")");
        return sb.toString();
    }
}
